export const BASE_EXP: Record<string, number> = {
	"bulbasaur": 64,
	"ivysaur": 142,
	"venusaur": 236,
	"charmander": 62,
	"charmeleon": 142,
	"charizard": 240,
	"squirtle": 63,
	"wartortle": 142,
	"blastoise": 239,
	"caterpie": 39,
	"metapod": 72,
	"butterfree": 178,
	"weedle": 39,
	"kakuna": 72,
	"beedrill": 178,
	"pidgey": 50,
	"pidgeotto": 122,
	"pidgeot": 216,
	"rattata": 51,
	"raticate": 145,
	"spearow": 52,
	"fearow": 155,
	"ekans": 58,
	"arbok": 157,
	"pikachu": 112,
	"raichu": 218,
	"sandshrew": 60,
	"sandslash": 158,
	"nidoranf": 55,
	"nidorina": 128,
	"nidoqueen": 227,
	"nidoranm": 55,
	"nidorino": 128,
	"nidoking": 227,
	"clefairy": 113,
	"clefable": 217,
	"vulpix": 60,
	"ninetales": 177,
	"jigglypuff": 95,
	"wigglytuff": 196,
	"zubat": 49,
	"golbat": 159,
	"oddish": 64,
	"gloom": 138,
	"vileplume": 221,
	"paras": 57,
	"parasect": 142,
	"venonat": 61,
	"venomoth": 158,
	"diglett": 53,
	"dugtrio": 149,
	"meowth": 58,
	"persian": 154,
	"psyduck": 64,
	"golduck": 175,
	"mankey": 61,
	"primeape": 159,
	"growlithe": 70,
	"arcanine": 194,
	"poliwag": 60,
	"poliwhirl": 135,
	"poliwrath": 230,
	"abra": 62,
	"kadabra": 140,
	"alakazam": 225,
	"machop": 61,
	"machoke": 142,
	"machamp": 227,
	"bellsprout": 60,
	"weepinbell": 137,
	"victreebel": 221,
	"tentacool": 67,
	"tentacruel": 180,
	"geodude": 60,
	"graveler": 137,
	"golem": 223,
	"ponyta": 82,
	"rapidash": 175,
	"slowpoke": 63,
	"slowbro": 172,
	"magnemite": 65,
	"magneton": 163,
	"farfetchd": 132,
	"doduo": 62,
	"dodrio": 165,
	"seel": 65,
	"dewgong": 166,
	"grimer": 65,
	"muk": 175,
	"shellder": 61,
	"cloyster": 184,
	"gastly": 62,
	"haunter": 142,
	"gengar": 225,
	"onix": 77,
	"drowzee": 66,
	"hypno": 169,
	"krabby": 65,
	"kingler": 166,
	"voltorb": 66,
	"electrode": 172,
	"exeggcute": 65,
	"exeggutor": 186,
	"cubone": 64,
	"marowak": 149,
	"hitmonlee": 159,
	"hitmonchan": 159,
	"lickitung": 77,
	"koffing": 68,
	"weezing": 172,
	"rhyhorn": 69,
	"rhydon": 170,
	"chansey": 395,
	"tangela": 87,
	"kangaskhan": 172,
	"horsea": 59,
	"seadra": 154,
	"goldeen": 64,
	"seaking": 158,
	"staryu": 68,
	"starmie": 182,
	"mrmime": 161,
	"scyther": 100,
	"jynx": 159,
	"electabuzz": 172,
	"magmar": 173,
	"pinsir": 175,
	"tauros": 172,
	"magikarp": 40,
	"gyarados": 189,
	"lapras": 187,
	"ditto": 101,
	"eevee": 65,
	"vaporeon": 184,
	"jolteon": 184,
	"flareon": 184,
	"porygon": 79,
	"omanyte": 71,
	"omastar": 173,
	"kabuto": 71,
	"kabutops": 173,
	"aerodactyl": 180,
	"snorlax": 189,
	"articuno": 261,
	"zapdos": 261,
	"moltres": 261,
	"dratini": 60,
	"dragonair": 147,
	"dragonite": 270,
	"mewtwo": 306,
	"mew": 270,
	"chikorita": 64,
	"bayleef": 142,
	"meganium": 236,
	"cyndaquil": 62,
	"quilava": 142,
	"typhlosion": 240,
	"totodile": 63,
	"croconaw": 142,
	"feraligatr": 239,
	"sentret": 43,
	"furret": 145,
	"hoothoot": 52,
	"noctowl": 158,
	"ledyba": 53,
	"ledian": 137,
	"spinarak": 50,
	"ariados": 140,
	"crobat": 241,
	"chinchou": 66,
	"lanturn": 161,
	"pichu": 41,
	"cleffa": 44,
	"igglybuff": 42,
	"togepi": 49,
	"togetic": 142,
	"natu": 64,
	"xatu": 165,
	"mareep": 56,
	"flaaffy": 128,
	"ampharos": 230,
	"bellossom": 221,
	"marill": 88,
	"azumarill": 189,
	"sudowoodo": 144,
	"politoed": 225,
	"hoppip": 50,
	"skiploom": 119,
	"jumpluff": 207,
	"aipom": 72,
	"sunkern": 36,
	"sunflora": 149,
	"yanma": 78,
	"wooper": 42,
	"quagsire": 151,
	"espeon": 184,
	"umbreon": 184,
	"murkrow": 81,
	"slowking": 172,
	"misdreavus": 87,
	"unown": 118,
	"wobbuffet": 142,
	"girafarig": 159,
	"pineco": 58,
	"forretress": 163,
	"dunsparce": 145,
	"gligar": 86,
	"steelix": 179,
	"snubbull": 60,
	"granbull": 158,
	"qwilfish": 88,
	"scizor": 175,
	"shuckle": 177,
	"heracross": 175,
	"sneasel": 86,
	"teddiursa": 66,
	"ursaring": 175,
	"slugma": 50,
	"magcargo": 151,
	"swinub": 50,
	"piloswine": 158,
	"corsola": 144,
	"remoraid": 60,
	"octillery": 168,
	"delibird": 116,
	"mantine": 170,
	"skarmory": 163,
	"houndour": 66,
	"houndoom": 175,
	"kingdra": 243,
	"phanpy": 66,
	"donphan": 175,
	"porygon2": 180,
	"stantler": 163,
	"smeargle": 88,
	"tyrogue": 42,
	"hitmontop": 159,
	"smoochum": 61,
	"elekid": 72,
	"magby": 73,
	"miltank": 172,
	"blissey": 608,
	"raikou": 261,
	"entei": 261,
	"suicune": 261,
	"larvitar": 60,
	"pupitar": 144,
	"tyranitar": 270,
	"lugia": 306,
	"hooh": 306,
	"celebi": 270,
	"treecko": 62,
	"grovyle": 142,
	"sceptile": 239,
	"torchic": 62,
	"combusken": 142,
	"blaziken": 239,
	"mudkip": 62,
	"marshtomp": 142,
	"swampert": 241,
	"poochyena": 56,
	"mightyena": 147,
	"zigzagoon": 56,
	"linoone": 147,
	"wurmple": 56,
	"silcoon": 72,
	"beautifly": 178,
	"cascoon": 72,
	"dustox": 173,
	"lotad": 44,
	"lombre": 119,
	"ludicolo": 216,
	"seedot": 44,
	"nuzleaf": 119,
	"shiftry": 216,
	"taillow": 54,
	"swellow": 159,
	"wingull": 54,
	"pelipper": 154,
	"ralts": 40,
	"kirlia": 97,
	"gardevoir": 233,
	"surskit": 54,
	"masquerain": 159,
	"shroomish": 59,
	"breloom": 161,
	"slakoth": 56,
	"vigoroth": 154,
	"slaking": 252,
	"nincada": 53,
	"ninjask": 160,
	"shedinja": 83,
	"whismur": 48,
	"loudred": 126,
	"exploud": 221,
	"makuhita": 47,
	"hariyama": 166,
	"azurill": 38,
	"nosepass": 75,
	"skitty": 52,
	"delcatty": 140,
	"sableye": 133,
	"mawile": 133,
	"aron": 66,
	"lairon": 151,
	"aggron": 239,
	"meditite": 56,
	"medicham": 144,
	"electrike": 59,
	"manectric": 166,
	"plusle": 142,
	"minun": 142,
	"volbeat": 151,
	"illumise": 151,
	"roselia": 140,
	"gulpin": 60,
	"swalot": 163,
	"carvanha": 61,
	"sharpedo": 161,
	"wailmer": 80,
	"wailord": 175,
	"numel": 61,
	"camerupt": 161,
	"torkoal": 165,
	"spoink": 66,
	"grumpig": 165,
	"spinda": 126,
	"trapinch": 58,
	"vibrava": 119,
	"flygon": 234,
	"cacnea": 67,
	"cacturne": 166,
	"swablu": 62,
	"alt": 172,
	"zangoose": 160,
	"seviper": 160,
	"lunatone": 161,
	"solrock": 161,
	"barboach": 58,
	"whiscash": 164,
	"corphish": 62,
	"crawdaunt": 164,
	"baltoy": 60,
	"claydol": 175,
	"lileep": 71,
	"cradily": 173,
	"anorith": 71,
	"armaldo": 173,
	"feebas": 40,
	"milotic": 189,
	"castform": 147,
	"kecleon": 154,
	"shuppet": 59,
	"banette": 159,
	"duskull": 59,
	"dusclops": 159,
	"tropius": 161,
	"chimecho": 159,
	"absol": 163,
	"wynaut": 52,
	"snorunt": 60,
	"glalie": 168,
	"spheal": 58,
	"sealeo": 144,
	"walrein": 239,
	"clamperl": 69,
	"huntail": 170,
	"gorebyss": 170,
	"relicanth": 170,
	"luvdisc": 116,
	"bagon": 60,
	"shelgon": 147,
	"salamence": 270,
	"beldum": 60,
	"metang": 147,
	"metagross": 270,
	"regirock": 261,
	"reg": 261,
	"registeel": 261,
	"latias": 270,
	"latios": 270,
	"kyogre": 302,
	"groudon": 302,
	"rayquaza": 306,
	"jirachi": 270,
	"deoxys": 270,
	"turtwig": 64,
	"grotle": 142,
	"torterra": 236,
	"chimchar": 62,
	"monferno": 142,
	"infernape": 240,
	"piplup": 63,
	"prinplup": 142,
	"empoleon": 239,
	"starly": 49,
	"staravia": 119,
	"staraptor": 218,
	"bidoof": 50,
	"bibarel": 144,
	"kricketot": 39,
	"kricketune": 134,
	"shinx": 53,
	"luxio": 127,
	"luxray": 235,
	"budew": 56,
	"roserade": 232,
	"cranidos": 70,
	"rampardos": 173,
	"shieldon": 70,
	"bastiodon": 173,
	"burmy": 45,
	"wormadamplant": 148,
	"mothim": 148,
	"combee": 49,
	"vespiquen": 166,
	"pachirisu": 142,
	"buizel": 66,
	"floatzel": 173,
	"cherubi": 55,
	"cherrim": 158,
	"shellos": 65,
	"gastrodon": 166,
	"ambipom": 169,
	"drifloon": 70,
	"drifblim": 174,
	"buneary": 70,
	"lopunny": 168,
	"mismagius": 173,
	"honchkrow": 177,
	"glameow": 62,
	"purugly": 158,
	"chingling": 57,
	"stunky": 66,
	"skuntank": 168,
	"bronzor": 60,
	"bronzong": 175,
	"bonsly": 58,
	"mimejr": 62,
	"happiny": 110,
	"chatot": 144,
	"spiritomb": 170,
	"gible": 60,
	"gabite": 144,
	"garchomp": 270,
	"munchlax": 78,
	"riolu": 57,
	"lucario": 184,
	"hippopotas": 66,
	"hippowdon": 184,
	"skorupi": 66,
	"drapion": 175,
	"croagunk": 60,
	"toxicroak": 172,
	"carnivine": 159,
	"finneon": 66,
	"lumineon": 161,
	"mantyke": 69,
	"snover": 67,
	"abomasnow": 173,
	"weavile": 179,
	"magnezone": 241,
	"lickilicky": 180,
	"rhyperior": 241,
	"tangrowth": 187,
	"electivire": 243,
	"magmortar": 243,
	"togekiss": 245,
	"yanmega": 180,
	"leafeon": 184,
	"glaceon": 184,
	"gliscor": 179,
	"mamoswine": 239,
	"porygonz": 241,
	"gallade": 233,
	"probopass": 184,
	"dusknoir": 236,
	"froslass": 168,
	"rotom": 154,
	"uxie": 261,
	"mesprit": 261,
	"azelf": 261,
	"dialga": 306,
	"palkia": 306,
	"heatran": 270,
	"regigigas": 302,
	"giratina": 306,
	"cresselia": 270,
	"phione": 216,
	"manaphy": 270,
	"darkrai": 270,
	"shayminland": 270,
	"arceus": 324,
	"victini": 270,
	"snivy": 62,
	"servine": 145,
	"serperior": 238,
	"tepig": 62,
	"pignite": 146,
	"emboar": 238,
	"oshawott": 62,
	"dewott": 145,
	"samurott": 238,
	"patrat": 51,
	"watchog": 147,
	"lillipup": 55,
	"herdier": 130,
	"stoutland": 225,
	"purrloin": 56,
	"liepard": 156,
	"pansage": 63,
	"simisage": 174,
	"pansear": 63,
	"simisear": 174,
	"panpour": 63,
	"simipour": 174,
	"munna": 58,
	"musharna": 170,
	"pidove": 53,
	"tranquill": 125,
	"unfezant": 220,
	"blitzle": 59,
	"zebstrika": 174,
	"roggenrola": 56,
	"boldore": 137,
	"gigalith": 232,
	"woobat": 65,
	"swoobat": 149,
	"drilbur": 66,
	"excadrill": 178,
	"audino": 390,
	"timburr": 61,
	"gurdurr": 142,
	"conkeldurr": 227,
	"tympole": 59,
	"palpitoad": 134,
	"seismitoad": 229,
	"throh": 163,
	"sawk": 163,
	"sewaddle": 62,
	"swadloon": 133,
	"leavanny": 225,
	"venipede": 52,
	"whirlipede": 126,
	"scolipede": 218,
	"cottonee": 56,
	"whimsicott": 168,
	"petilil": 56,
	"lilligant": 168,
	"basculinredstriped": 161,
	"sandile": 58,
	"krokorok": 123,
	"krookodile": 234,
	"darumaka": 63,
	"darmanitan": 168,
	"maractus": 161,
	"dwebble": 65,
	"crustle": 170,
	"scraggy": 70,
	"scrafty": 171,
	"sigilyph": 172,
	"yamask": 61,
	"cofagrigus": 169,
	"tirtouga": 71,
	"carracosta": 173,
	"archen": 71,
	"archeops": 177,
	"trubbish": 66,
	"garbodor": 166,
	"zorua": 66,
	"zoroark": 179,
	"minccino": 60,
	"cinccino": 165,
	"gothita": 58,
	"gothorita": 137,
	"gothitelle": 221,
	"solosis": 58,
	"duosion": 130,
	"reuniclus": 221,
	"ducklett": 61,
	"swanna": 166,
	"vanillite": 61,
	"vanillish": 138,
	"vanilluxe": 241,
	"deerling": 67,
	"sawsbuck": 166,
	"emolga": 150,
	"karrablast": 63,
	"escavalier": 173,
	"foongus": 59,
	"amoonguss": 162,
	"frillish": 67,
	"jellicent": 168,
	"alomomola": 165,
	"joltik": 64,
	"galvantula": 165,
	"ferroseed": 61,
	"ferrothorn": 171,
	"klink": 60,
	"klang": 154,
	"klinklang": 234,
	"tynamo": 55,
	"eelektrik": 142,
	"eelektross": 232,
	"elgyem": 67,
	"beheeyem": 170,
	"litwick": 55,
	"lampent": 130,
	"chandelure": 234,
	"axew": 64,
	"fraxure": 144,
	"haxorus": 243,
	"cubchoo": 61,
	"beartic": 177,
	"cryogonal": 180,
	"shelmet": 61,
	"accelgor": 173,
	"stunfisk": 165,
	"mienfoo": 70,
	"mienshao": 179,
	"druddigon": 170,
	"golett": 61,
	"golurk": 169,
	"pawniard": 68,
	"bisharp": 172,
	"bouffalant": 172,
	"rufflet": 70,
	"braviary": 179,
	"vullaby": 74,
	"mandibuzz": 179,
	"heatmor": 169,
	"durant": 169,
	"deino": 60,
	"zweilous": 147,
	"hydreigon": 270,
	"larvesta": 72,
	"volcarona": 248,
	"cobalion": 261,
	"terrakion": 261,
	"virizion": 261,
	"tornadus": 261,
	"thundurus": 261,
	"reshiram": 306,
	"zekrom": 306,
	"landorus": 270,
	"kyurem": 297,
	"keldeo": 261,
	"meloetta": 270,
	"genesect": 270,
	"chespin": 63,
	"quilladin": 142,
	"chesnaught": 239,
	"fennekin": 61,
	"braixen": 143,
	"delphox": 240,
	"froakie": 63,
	"frogadier": 142,
	"greninja": 239,
	"bunnelby": 47,
	"diggersby": 148,
	"fletchling": 56,
	"fletchinder": 134,
	"talonflame": 175,
	"scatterbug": 40,
	"spewpa": 75,
	"vivillon": 185,
	"litleo": 74,
	"pyroar": 177,
	"flabebe": 61,
	"floette": 130,
	"florges": 248,
	"skiddo": 70,
	"gogoat": 186,
	"pancham": 70,
	"pangoro": 173,
	"furfrou": 165,
	"espurr": 71,
	"meowstic": 163,
	"honedge": 65,
	"doublade": 157,
	"aegislash": 234,
	"spritzee": 68,
	"aromatisse": 162,
	"swirlix": 68,
	"slurpuff": 168,
	"inkay": 58,
	"malamar": 169,
	"binacle": 61,
	"barbaracle": 175,
	"skrelp": 64,
	"dragalge": 173,
	"clauncher": 66,
	"clawitzer": 100,
	"helioptile": 58,
	"heliolisk": 168,
	"tyrunt": 72,
	"tyrantrum": 182,
	"amaura": 72,
	"aurorus": 104,
	"sylveon": 184,
	"hawlucha": 175,
	"dedenne": 151,
	"carbink": 100,
	"goomy": 60,
	"sliggoo": 158,
	"goodra": 270,
	"klefki": 165,
	"phantump": 62,
	"trevenant": 166,
	"pumpkaboo": 67,
	"gourgeist": 173,
	"bergmite": 61,
	"avalugg": 180,
	"noibat": 49,
	"noivern": 187,
	"xerneas": 306,
	"yveltal": 306,
	"zygarde50": 270,
	"diancie": 270,
	"hoopa": 270,
	"volcanion": 270,
	"rowlet": 64,
	"dartrix": 147,
	"decidueye": 239,
	"litten": 64,
	"torracat": 147,
	"incineroar": 239,
	"popplio": 64,
	"brionne": 147,
	"primarina": 239,
	"pikipek": 53,
	"trumbeak": 124,
	"toucannon": 218,
	"yungoos": 51,
	"gumshoos": 146,
	"grubbin": 60,
	"charjabug": 140,
	"vikavolt": 225,
	"crabrawler": 68,
	"crabominable": 167,
	"oricorio": 167,
	"cutiefly": 61,
	"ribombee": 162,
	"rockruff": 56,
	"lycanroc": 170,
	"wishiwashi": 61,
	"mareanie": 61,
	"toxapex": 173,
	"mudbray": 77,
	"mudsdale": 175,
	"dewpider": 54,
	"araquanid": 159,
	"fomantis": 50,
	"lurantis": 168,
	"morelull": 57,
	"shiinotic": 142,
	"salandit": 64,
	"salazzle": 168,
	"stufful": 68,
	"bewear": 175,
	"bounsweet": 42,
	"steenee": 102,
	"tsareena": 230,
	"comfey": 170,
	"oranguru": 172,
	"passimian": 172,
	"wimpod": 46,
	"golisopod": 186,
	"sandygast": 64,
	"palossand": 168,
	"pyukumuku": 144,
	"typenull": 107,
	"silvally": 257,
	"minior": 154,
	"komala": 168,
	"turtonator": 170,
	"togedemaru": 152,
	"mimikyu": 167,
	"bruxish": 166,
	"drampa": 170,
	"dhelmise": 181,
	"jangmoo": 60,
	"hakamoo": 147,
	"kommoo": 270,
	"tapukoko": 257,
	"tapulele": 257,
	"tapubulu": 257,
	"tapufini": 257,
	"cosmog": 40,
	"cosmoem": 140,
	"solgaleo": 306,
	"lunala": 306,
	"nihilego": 257,
	"buzzwole": 257,
	"pheromosa": 257,
	"xurkitree": 257,
	"celesteela": 257,
	"kartana": 257,
	"guzzlord": 257,
	"necrozma": 270,
	"magearna": 270,
	"marshadow": 270,
	"poipole": 189,
	"naganadel": 243,
	"stakataka": 257,
	"blacephalon": 257,
	"zeraora": 270,
	"meltan": 135,
	"melmetal": 270,
	"grookey": 62,
	"thwackey": 147,
	"rillaboom": 265,
	"scorbunny": 62,
	"raboot": 147,
	"cinderace": 265,
	"sobble": 62,
	"drizzile": 147,
	"inteleon": 265,
	"skwovet": 55,
	"greedent": 161,
	"rookidee": 49,
	"corvisquire": 128,
	"corviknight": 248,
	"blipbug": 36,
	"dottler": 117,
	"orbeetle": 253,
	"nickit": 49,
	"thievul": 159,
	"gossifleur": 50,
	"eldegoss": 161,
	"wooloo": 122,
	"dubwool": 172,
	"chewtle": 57,
	"drednaw": 170,
	"yamper": 54,
	"boltund": 172,
	"rolycoly": 48,
	"carkol": 144,
	"coalossal": 255,
	"applin": 52,
	"flapple": 170,
	"appletun": 170,
	"silicobra": 63,
	"sandaconda": 179,
	"cramorant": 166,
	"arrokuda": 56,
	"barraskewda": 172,
	"toxel": 48,
	"toxtricity": 176,
	"sizzlipede": 61,
	"centiskorch": 184,
	"clobbopus": 62,
	"grapploct": 168,
	"sinistea": 62,
	"polteageist": 178,
	"hatenna": 53,
	"hattrem": 130,
	"hatterene": 255,
	"impidimp": 53,
	"morgrem": 130,
	"grimmsnarl": 255,
	"obstagoon": 260,
	"perrserker": 154,
	"cursola": 179,
	"sirfetchd": 177,
	"mrrime": 182,
	"runerigus": 169,
	"milcery": 54,
	"alcremie": 173,
	"falinks": 165,
	"pincurchin": 152,
	"snom": 37,
	"frosmoth": 166,
	"stonjourner": 165,
	"eiscue": 165,
	"indeedee": 166,
	"morpeko": 153,
	"cufant": 66,
	"copperajah": 175,
	"dracozolt": 177,
	"arctozolt": 177,
	"dracovish": 177,
	"arctovish": 177,
	"duraludon": 187,
	"dreepy": 54,
	"drakloak": 144,
	"dragapult": 300,
	"zacian": 335,
	"zamazenta": 335,
	"eternatus": 345,
	"kubfu": 77,
	"urshifu": 275,
	"zarude": 300,
	"regieleki": 290,
	"regidrago": 290,
	"glastrier": 290,
	"spectrier": 290,
	"calyrex": 340,
	"wyrdeer": 263,
	"kleavor": 175,
	"ursaluna": 275,
	"basculegion": 265,
	"sneasler": 102,
	"overqwil": 179,
	"enamorus": 116,
	"sprigatito": 62,
	"floragato": 144,
	"meowscarada": 265,
	"fuecoco": 62,
	"crocalor": 144,
	"skeledirge": 265,
	"quaxly": 62,
	"quaxwell": 144,
	"quaquaval": 265,
	"lechonk": 51,
	"oinkologne": 171,
	"tarountula": 42,
	"spidops": 141,
	"nymble": 42,
	"lokix": 158,
	"pawmi": 48,
	"pawmo": 123,
	"pawmot": 245,
	"tandemaus": 61,
	"mausholdfamilyoffour": 165,
	"fidough": 62,
	"dachsbun": 167,
	"smoliv": 52,
	"dolliv": 124,
	"arboliva": 255,
	"squawkabillygreenplumage": 146,
	"nacli": 56,
	"naclstack": 124,
	"garganacl": 250,
	"charcadet": 51,
	"armarouge": 263,
	"ceruledge": 263,
	"tadbulb": 54,
	"bellibolt": 173,
	"wattrel": 56,
	"kilowattrel": 172,
	"maschiff": 68,
	"mabosstiff": 177,
	"shroodle": 58,
	"grafaiai": 170,
	"bramblin": 55,
	"brambleghast": 168,
	"toedscool": 67,
	"toedscruel": 180,
	"klawf": 158,
	"capsakid": 61,
	"scovillain": 170,
	"rellor": 54,
	"rabsca": 165,
	"flittle": 51,
	"espathra": 168,
	"tinkatink": 59,
	"tinkatuff": 133,
	"tinkaton": 253,
	"wiglett": 49,
	"wugtrio": 149,
	"bombirdier": 243,
	"finizen": 63,
	"palafinzero": 160,
	"varoom": 60,
	"revavroom": 175,
	"cyclizar": 175,
	"orthworm": 240,
	"glimmet": 70,
	"glimmora": 184,
	"greavard": 58,
	"houndstone": 171,
	"flamigo": 175,
	"cetoddle": 67,
	"cetitan": 182,
	"veluza": 167,
	"dondozo": 265,
	"tatsugiricurly": 166,
	"annihilape": 268,
	"clodsire": 151,
	"farigiraf": 260,
	"dudunsparcetwosegment": 182,
	"kingambit": 275,
	"greattusk": 285,
	"screamtail": 285,
	"brutebonnet": 285,
	"fluttermane": 285,
	"slitherwing": 285,
	"sandyshocks": 285,
	"irontreads": 285,
	"ironbundle": 285,
	"ironhands": 285,
	"ironjugulis": 285,
	"ironmoth": 285,
	"ironthorns": 285,
	"frigibax": 64,
	"arctibax": 148,
	"baxcalibur": 300,
	"gimmighoul": 60,
	"gholdengo": 275,
	"wochien": 285,
	"chienpao": 285,
	"tinglu": 285,
	"chiyu": 285,
	"roaringmoon": 295,
	"ironvaliant": 295,
	"koraidon": 335,
	"miraidon": 335,
	"walkingwake": 295,
	"ironleaves": 295,
	"dipplin": 170,
	"poltchageist": 62,
	"sinistcha": 178,
	"okidogi": 278,
	"munkidori": 278,
	"fezandipiti": 278,
	"ogerpon": 275,
	"archaludon": 300,
	"hydrapple": 270,
	"gougingfire": 295,
	"ragingbolt": 295,
	"ironboulder": 295,
	"ironcrown": 295,
	"terapagos": 90,
	"pecharunt": 300,
	"deoxysattack": 270,
	"deoxysdefense": 270,
	"deoxysspeed": 270,
	"wormadamsandy": 148,
	"wormadamtrash": 148,
	"shayminsky": 270,
	"giratinaorigin": 340,
	"rotomheat": 182,
	"rotomwash": 182,
	"rotomfrost": 182,
	"rotomfan": 182,
	"rotommow": 182,
	"castformsunny": 147,
	"castformrainy": 147,
	"castformsnowy": 147,
	"basculinbluestriped": 161,
	"darmanitanzen": 189,
	"meloettapirouette": 270,
	"tornadustherian": 290,
	"thundurustherian": 290,
	"landorustherian": 300,
	"kyuremblack": 350,
	"kyuremwhite": 350,
	"keldeoresolute": 290,
	"meowsticfe": 163,
	"aegislashblade": 250,
	"pumpkaboosmall": 67,
	"pumpkaboolarge": 67,
	"pumpkaboosuper": 67,
	"gourgeistsmall": 173,
	"gourgeistlarge": 173,
	"gourgeistsuper": 173,
	"venusaurmega": 281,
	"charizardmegax": 285,
	"charizardmegay": 285,
	"blastoisemega": 284,
	"alakazammega": 270,
	"gengarmega": 270,
	"kangaskhanmega": 207,
	"pinsirmega": 210,
	"gyaradosmega": 224,
	"aerodactylmega": 215,
	"mewtwomegax": 351,
	"mewtwomegay": 351,
	"ampharosmega": 275,
	"scizormega": 210,
	"heracrossmega": 210,
	"houndoommega": 210,
	"tyranitarmega": 315,
	"blazikenmega": 284,
	"gardevoirmega": 278,
	"mawilemega": 168,
	"aggronmega": 284,
	"medichammega": 179,
	"manectricmega": 201,
	"banettemega": 194,
	"absolmega": 198,
	"garchompmega": 315,
	"lucariomega": 219,
	"abomasnowmega": 208,
	"floetteeternal": 243,
	"latiasmega": 315,
	"latiosmega": 315,
	"swampertmega": 286,
	"sceptilemega": 284,
	"sableyemega": 168,
	"altariamega": 207,
	"gallademega": 278,
	"audinomega": 425,
	"sharpedomega": 196,
	"slowbromega": 207,
	"steelixmega": 214,
	"pidgeotmega": 261,
	"glaliemega": 203,
	"dianciemega": 315,
	"metagrossmega": 315,
	"kyogreprimal": 347,
	"groudonprimal": 347,
	"rayquazamega": 351,
	"pikachurockstar": 112,
	"pikachubelle": 112,
	"pikachupopstar": 112,
	"pikachuphd": 112,
	"pikachulibre": 112,
	"pikachucosplay": 112,
	"hoopaunbound": 306,
	"cameruptmega": 196,
	"lopunnymega": 203,
	"salamencemega": 315,
	"beedrillmega": 223,
	"rattataalola": 51,
	"raticatealola": 145,
	"raticatetotemalola": 145,
	"pikachuoriginalcap": 112,
	"pikachuhoenncap": 112,
	"pikachusinnohcap": 112,
	"pikachuunovacap": 112,
	"pikachukaloscap": 112,
	"pikachualolacap": 112,
	"raichualola": 243,
	"sandshrewalola": 60,
	"sandslashalola": 158,
	"vulpixalola": 60,
	"ninetalesalola": 177,
	"diglettalola": 53,
	"dugtrioalola": 149,
	"meowthalola": 58,
	"persianalola": 154,
	"geodudealola": 60,
	"graveleralola": 137,
	"golemalola": 223,
	"grimeralola": 65,
	"mukalola": 175,
	"exeggutoralola": 186,
	"marowakalola": 149,
	"greninjabattlebond": 239,
	"greninjaash": 288,
	"zygarde10powerconstruct": 243,
	"zygarde50powerconstruct": 300,
	"zygardecomplete": 354,
	"gumshoostotem": 146,
	"vikavolttotem": 225,
	"oricoriopompom": 167,
	"oricoriopau": 167,
	"oricoriosensu": 167,
	"lycanrocmidnight": 170,
	"wishiwashischool": 217,
	"lurantistotem": 168,
	"salazzletotem": 168,
	"miniororangemeteor": 154,
	"minioryellowmeteor": 154,
	"miniorgreenmeteor": 154,
	"miniorbluemeteor": 154,
	"miniorindigometeor": 154,
	"miniorvioletmeteor": 154,
	"miniorred": 175,
	"miniororange": 175,
	"minioryellow": 175,
	"miniorgreen": 175,
	"miniorblue": 175,
	"miniorindigo": 175,
	"miniorviolet": 175,
	"mimikyubusted": 167,
	"mimikyutotem": 167,
	"mimikyutotembusted": 167,
	"kommoototem": 270,
	"magearnaoriginal": 300,
	"pikachupartnercap": 112,
	"marowaktotem": 149,
	"ribombeetotem": 162,
	"rockruffowntempo": 56,
	"lycanrocdusk": 170,
	"araquanidtotem": 159,
	"togedemarutotem": 152,
	"necrozmadusk": 340,
	"necrozmadawn": 340,
	"necrozmaultra": 339,
	"pikachustarter": 86,
	"eeveestarter": 87,
	"pikachuworldcap": 112,
	"meowthgalar": 58,
	"ponytagalar": 82,
	"rapidashgalar": 175,
	"slowpokegalar": 63,
	"slowbrogalar": 172,
	"farfetchdgalar": 132,
	"weezinggalar": 172,
	"mrmimegalar": 161,
	"articunogalar": 290,
	"zapdosgalar": 290,
	"moltresgalar": 290,
	"slowkinggalar": 172,
	"corsolagalar": 144,
	"zigzagoongalar": 56,
	"linoonegalar": 147,
	"darumakagalar": 63,
	"darmanitangalar": 168,
	"darmanitangalarzen": 189,
	"yamaskgalar": 61,
	"stunfiskgalar": 165,
	"zygarde10": 243,
	"cramorantgulping": 166,
	"cramorantgorging": 166,
	"toxtricitylowkey": 176,
	"eiscueno": 165,
	"indeedeefe": 166,
	"morpekohangry": 153,
	"zaciancrowned": 360,
	"zamazentacrowned": 360,
	"eternatuseternamax": 563,
	"urshifurapidstrike": 275,
	"zarudedada": 300,
	"calyrexshadow": 340,
	"venusaurgmax": 236,
	"charizardgmax": 240,
	"blastoisegmax": 239,
	"butterfreegmax": 178,
	"pikachugmax": 112,
	"meowthgmax": 58,
	"machampgmax": 227,
	"gengargmax": 225,
	"kinglergmax": 166,
	"laprasgmax": 187,
	"eeveegmax": 65,
	"snorlaxgmax": 189,
	"garbodorgmax": 166,
	"melmetalgmax": 270,
	"rillaboomgmax": 265,
	"cinderacegmax": 265,
	"inteleongmax": 265,
	"corviknightgmax": 248,
	"orbeetlegmax": 253,
	"drednawgmax": 170,
	"coalossalgmax": 255,
	"flapplegmax": 170,
	"appletungmax": 170,
	"sandacondagmax": 179,
	"toxtricityampedgmax": 176,
	"centiskorchgmax": 184,
	"hatterenegmax": 255,
	"grimmsnarlgmax": 255,
	"alcremiegmax": 173,
	"copperajahgmax": 175,
	"duraludongmax": 187,
	"urshifusinglestrikegmax": 275,
	"urshifurapidstrikegmax": 275,
	"toxtricitylowkeygmax": 176,
	"growlithehisui": 70,
	"arcaninehisui": 194,
	"voltorbhisui": 66,
	"electrodehisui": 172,
	"typhlosionhisui": 240,
	"qwilfishhisui": 88,
	"sneaselhisui": 86,
	"samurotthisui": 238,
	"lilliganthisui": 168,
	"zoruahisui": 66,
	"zoroarkhisui": 179,
	"braviaryhisui": 179,
	"sliggoohisui": 158,
	"goodrahisui": 270,
	"avalugghisui": 180,
	"decidueyehisui": 239,
	"dialgaorigin": 306,
	"palkiaorigin": 306,
	"basculinwhitestriped": 161,
	"basculegionfe": 265,
	"enamorustherian": 116,
	"taurospaldeacombatbreed": 172,
	"taurospaldeablazebreed": 172,
	"taurospaldeaaquabreed": 172,
	"wooperpaldea": 42,
	"oinkolognefe": 171,
	"dudunsparcethreesegment": 182,
	"palafinhero": 160,
	"mausholdfamilyofthree": 165,
	"tatsugiridroopy": 166,
	"tatsugiristretchy": 166,
	"squawkabillyblueplumage": 146,
	"squawkabillyyellowplumage": 146,
	"squawkabillywhiteplumage": 146,
	"gimmighoulroaming": 60,
	"koraidonlimitedbuild": 335,
	"koraidonsprintingbuild": 335,
	"koraidonswimmingbuild": 335,
	"koraidonglidingbuild": 335,
	"miraidonlowpowermode": 335,
	"miraidondrivemode": 335,
	"miraidonaquaticmode": 335,
	"miraidonglidemode": 335,
	"ursalunabloodmoon": 275,
	"ogerponwellspringmask": 275,
	"ogerponhearthflamemask": 275,
	"ogerponcornerstonemask": 275,
	"terapagosterastal": 90,
	"terapagosstellar": 90,
};

export const CATCH_RATES: Record<string, number> = {
	"bulbasaur": 45,
	"ivysaur": 45,
	"venusaur": 45,
	"charmander": 45,
	"charmeleon": 45,
	"charizard": 45,
	"squirtle": 45,
	"wartortle": 45,
	"blastoise": 45,
	"caterpie": 255,
	"metapod": 120,
	"butterfree": 45,
	"weedle": 255,
	"kakuna": 120,
	"beedrill": 45,
	"pidgey": 255,
	"pidgeotto": 120,
	"pidgeot": 45,
	"rattata": 255,
	"raticate": 127,
	"spearow": 255,
	"fearow": 90,
	"ekans": 255,
	"arbok": 90,
	"pikachu": 190,
	"raichu": 75,
	"sandshrew": 255,
	"sandslash": 90,
	"nidoranf": 235,
	"nidorina": 120,
	"nidoqueen": 45,
	"nidoranm": 235,
	"nidorino": 120,
	"nidoking": 45,
	"clefairy": 150,
	"clefable": 25,
	"vulpix": 190,
	"ninetales": 75,
	"jigglypuff": 170,
	"wigglytuff": 50,
	"zubat": 255,
	"golbat": 90,
	"oddish": 255,
	"gloom": 120,
	"vileplume": 45,
	"paras": 190,
	"parasect": 75,
	"venonat": 190,
	"venomoth": 75,
	"diglett": 255,
	"dugtrio": 50,
	"meowth": 255,
	"persian": 90,
	"psyduck": 190,
	"golduck": 75,
	"mankey": 190,
	"primeape": 75,
	"growlithe": 190,
	"arcanine": 75,
	"poliwag": 255,
	"poliwhirl": 120,
	"poliwrath": 45,
	"abra": 200,
	"kadabra": 100,
	"alakazam": 50,
	"machop": 180,
	"machoke": 90,
	"machamp": 45,
	"bellsprout": 255,
	"weepinbell": 120,
	"victreebel": 45,
	"tentacool": 190,
	"tentacruel": 60,
	"geodude": 255,
	"graveler": 120,
	"golem": 45,
	"ponyta": 190,
	"rapidash": 60,
	"slowpoke": 190,
	"slowbro": 75,
	"magnemite": 190,
	"magneton": 60,
	"farfetchd": 45,
	"doduo": 190,
	"dodrio": 45,
	"seel": 190,
	"dewgong": 75,
	"grimer": 190,
	"muk": 75,
	"shellder": 190,
	"cloyster": 60,
	"gastly": 190,
	"haunter": 90,
	"gengar": 45,
	"onix": 45,
	"drowzee": 190,
	"hypno": 75,
	"krabby": 225,
	"kingler": 60,
	"voltorb": 190,
	"electrode": 60,
	"exeggcute": 90,
	"exeggutor": 45,
	"cubone": 190,
	"marowak": 75,
	"hitmonlee": 45,
	"hitmonchan": 45,
	"lickitung": 45,
	"koffing": 190,
	"weezing": 60,
	"rhyhorn": 120,
	"rhydon": 60,
	"chansey": 30,
	"tangela": 45,
	"kangaskhan": 45,
	"horsea": 225,
	"seadra": 75,
	"goldeen": 225,
	"seaking": 60,
	"staryu": 225,
	"starmie": 60,
	"mrmime": 45,
	"scyther": 45,
	"jynx": 45,
	"electabuzz": 45,
	"magmar": 45,
	"pinsir": 45,
	"tauros": 45,
	"magikarp": 255,
	"gyarados": 45,
	"lapras": 45,
	"ditto": 35,
	"eevee": 45,
	"vaporeon": 45,
	"jolteon": 45,
	"flareon": 45,
	"porygon": 45,
	"omanyte": 45,
	"omastar": 45,
	"kabuto": 45,
	"kabutops": 45,
	"aerodactyl": 45,
	"snorlax": 25,
	"articuno": 3,
	"zapdos": 3,
	"moltres": 3,
	"dratini": 45,
	"dragonair": 45,
	"dragonite": 45,
	"mewtwo": 3,
	"mew": 45,
	"chikorita": 45,
	"bayleef": 45,
	"meganium": 45,
	"cyndaquil": 45,
	"quilava": 45,
	"typhlosion": 45,
	"totodile": 45,
	"croconaw": 45,
	"feraligatr": 45,
	"sentret": 255,
	"furret": 90,
	"hoothoot": 255,
	"noctowl": 90,
	"ledyba": 255,
	"ledian": 90,
	"spinarak": 255,
	"ariados": 90,
	"crobat": 90,
	"chinchou": 190,
	"lanturn": 75,
	"pichu": 190,
	"cleffa": 150,
	"igglybuff": 170,
	"togepi": 190,
	"togetic": 75,
	"natu": 190,
	"xatu": 75,
	"mareep": 235,
	"flaaffy": 120,
	"ampharos": 45,
	"bellossom": 45,
	"marill": 190,
	"azumarill": 75,
	"sudowoodo": 65,
	"politoed": 45,
	"hoppip": 255,
	"skiploom": 120,
	"jumpluff": 45,
	"aipom": 45,
	"sunkern": 235,
	"sunflora": 120,
	"yanma": 75,
	"wooper": 255,
	"quagsire": 90,
	"espeon": 45,
	"umbreon": 45,
	"murkrow": 30,
	"slowking": 70,
	"misdreavus": 45,
	"unown": 225,
	"wobbuffet": 45,
	"girafarig": 60,
	"pineco": 190,
	"forretress": 75,
	"dunsparce": 190,
	"gligar": 60,
	"steelix": 25,
	"snubbull": 190,
	"granbull": 75,
	"qwilfish": 45,
	"scizor": 25,
	"shuckle": 190,
	"heracross": 45,
	"sneasel": 60,
	"teddiursa": 120,
	"ursaring": 60,
	"slugma": 190,
	"magcargo": 75,
	"swinub": 225,
	"piloswine": 75,
	"corsola": 60,
	"remoraid": 190,
	"octillery": 75,
	"delibird": 45,
	"mantine": 25,
	"skarmory": 25,
	"houndour": 120,
	"houndoom": 45,
	"kingdra": 45,
	"phanpy": 120,
	"donphan": 60,
	"porygon2": 45,
	"stantler": 45,
	"smeargle": 45,
	"tyrogue": 75,
	"hitmontop": 45,
	"smoochum": 45,
	"elekid": 45,
	"magby": 45,
	"miltank": 45,
	"blissey": 30,
	"raikou": 3,
	"entei": 3,
	"suicune": 3,
	"larvitar": 45,
	"pupitar": 45,
	"tyranitar": 45,
	"lugia": 3,
	"hooh": 3,
	"celebi": 45,
	"treecko": 45,
	"grovyle": 45,
	"sceptile": 45,
	"torchic": 45,
	"combusken": 45,
	"blaziken": 45,
	"mudkip": 45,
	"marshtomp": 45,
	"swampert": 45,
	"poochyena": 255,
	"mightyena": 127,
	"zigzagoon": 255,
	"linoone": 90,
	"wurmple": 255,
	"silcoon": 120,
	"beautifly": 45,
	"cascoon": 120,
	"dustox": 45,
	"lotad": 255,
	"lombre": 120,
	"ludicolo": 45,
	"seedot": 255,
	"nuzleaf": 120,
	"shiftry": 45,
	"taillow": 200,
	"swellow": 45,
	"wingull": 190,
	"pelipper": 45,
	"ralts": 235,
	"kirlia": 120,
	"gardevoir": 45,
	"surskit": 200,
	"masquerain": 75,
	"shroomish": 255,
	"breloom": 90,
	"slakoth": 255,
	"vigoroth": 120,
	"slaking": 45,
	"nincada": 255,
	"ninjask": 120,
	"shedinja": 45,
	"whismur": 190,
	"loudred": 120,
	"exploud": 45,
	"makuhita": 180,
	"hariyama": 200,
	"azurill": 150,
	"nosepass": 255,
	"skitty": 255,
	"delcatty": 60,
	"sableye": 45,
	"mawile": 45,
	"aron": 180,
	"lairon": 90,
	"aggron": 45,
	"meditite": 180,
	"medicham": 90,
	"electrike": 120,
	"manectric": 45,
	"plusle": 200,
	"minun": 200,
	"volbeat": 150,
	"illumise": 150,
	"roselia": 150,
	"gulpin": 225,
	"swalot": 75,
	"carvanha": 225,
	"sharpedo": 60,
	"wailmer": 125,
	"wailord": 60,
	"numel": 255,
	"camerupt": 150,
	"torkoal": 90,
	"spoink": 255,
	"grumpig": 60,
	"spinda": 255,
	"trapinch": 255,
	"vibrava": 120,
	"flygon": 45,
	"cacnea": 190,
	"cacturne": 60,
	"swablu": 255,
	"alt": 45,
	"zangoose": 90,
	"seviper": 90,
	"lunatone": 45,
	"solrock": 45,
	"barboach": 190,
	"whiscash": 75,
	"corphish": 205,
	"crawdaunt": 155,
	"baltoy": 255,
	"claydol": 90,
	"lileep": 45,
	"cradily": 45,
	"anorith": 45,
	"armaldo": 45,
	"feebas": 255,
	"milotic": 60,
	"castform": 45,
	"kecleon": 200,
	"shuppet": 225,
	"banette": 45,
	"duskull": 190,
	"dusclops": 90,
	"tropius": 200,
	"chimecho": 45,
	"absol": 30,
	"wynaut": 125,
	"snorunt": 190,
	"glalie": 75,
	"spheal": 255,
	"sealeo": 120,
	"walrein": 45,
	"clamperl": 255,
	"huntail": 60,
	"gorebyss": 60,
	"relicanth": 25,
	"luvdisc": 225,
	"bagon": 45,
	"shelgon": 45,
	"salamence": 45,
	"beldum": 3,
	"metang": 3,
	"metagross": 3,
	"regirock": 3,
	"reg": 3,
	"registeel": 3,
	"latias": 3,
	"latios": 3,
	"kyogre": 3,
	"groudon": 3,
	"rayquaza": 45,
	"jirachi": 3,
	"deoxys": 3,
	"turtwig": 45,
	"grotle": 45,
	"torterra": 45,
	"chimchar": 45,
	"monferno": 45,
	"infernape": 45,
	"piplup": 45,
	"prinplup": 45,
	"empoleon": 45,
	"starly": 255,
	"staravia": 120,
	"staraptor": 45,
	"bidoof": 255,
	"bibarel": 127,
	"kricketot": 255,
	"kricketune": 45,
	"shinx": 235,
	"luxio": 120,
	"luxray": 45,
	"budew": 255,
	"roserade": 75,
	"cranidos": 45,
	"rampardos": 45,
	"shieldon": 45,
	"bastiodon": 45,
	"burmy": 120,
	"wormadamplant": 45,
	"mothim": 45,
	"combee": 120,
	"vespiquen": 45,
	"pachirisu": 200,
	"buizel": 190,
	"floatzel": 75,
	"cherubi": 190,
	"cherrim": 75,
	"shellos": 190,
	"gastrodon": 75,
	"ambipom": 45,
	"drifloon": 125,
	"drifblim": 60,
	"buneary": 190,
	"lopunny": 60,
	"mismagius": 45,
	"honchkrow": 30,
	"glameow": 190,
	"purugly": 75,
	"chingling": 120,
	"stunky": 225,
	"skuntank": 60,
	"bronzor": 255,
	"bronzong": 90,
	"bonsly": 255,
	"mimejr": 145,
	"happiny": 130,
	"chatot": 30,
	"spiritomb": 100,
	"gible": 45,
	"gabite": 45,
	"garchomp": 45,
	"munchlax": 50,
	"riolu": 75,
	"lucario": 45,
	"hippopotas": 140,
	"hippowdon": 60,
	"skorupi": 120,
	"drapion": 45,
	"croagunk": 140,
	"toxicroak": 75,
	"carnivine": 200,
	"finneon": 190,
	"lumineon": 75,
	"mantyke": 25,
	"snover": 120,
	"abomasnow": 60,
	"weavile": 45,
	"magnezone": 30,
	"lickilicky": 30,
	"rhyperior": 30,
	"tangrowth": 30,
	"electivire": 30,
	"magmortar": 30,
	"togekiss": 30,
	"yanmega": 30,
	"leafeon": 45,
	"glaceon": 45,
	"gliscor": 30,
	"mamoswine": 50,
	"porygonz": 30,
	"gallade": 45,
	"probopass": 60,
	"dusknoir": 45,
	"froslass": 75,
	"rotom": 45,
	"uxie": 3,
	"mesprit": 3,
	"azelf": 3,
	"dialga": 3,
	"palkia": 3,
	"heatran": 3,
	"regigigas": 3,
	"giratina": 3,
	"cresselia": 3,
	"phione": 30,
	"manaphy": 3,
	"darkrai": 3,
	"shayminland": 45,
	"arceus": 3,
	"victini": 3,
	"snivy": 45,
	"servine": 45,
	"serperior": 45,
	"tepig": 45,
	"pignite": 45,
	"emboar": 45,
	"oshawott": 45,
	"dewott": 45,
	"samurott": 45,
	"patrat": 255,
	"watchog": 255,
	"lillipup": 255,
	"herdier": 120,
	"stoutland": 45,
	"purrloin": 255,
	"liepard": 90,
	"pansage": 190,
	"simisage": 75,
	"pansear": 190,
	"simisear": 75,
	"panpour": 190,
	"simipour": 75,
	"munna": 190,
	"musharna": 75,
	"pidove": 255,
	"tranquill": 120,
	"unfezant": 45,
	"blitzle": 190,
	"zebstrika": 75,
	"roggenrola": 255,
	"boldore": 120,
	"gigalith": 45,
	"woobat": 190,
	"swoobat": 45,
	"drilbur": 120,
	"excadrill": 60,
	"audino": 255,
	"timburr": 180,
	"gurdurr": 90,
	"conkeldurr": 45,
	"tympole": 255,
	"palpitoad": 120,
	"seismitoad": 45,
	"throh": 45,
	"sawk": 45,
	"sewaddle": 255,
	"swadloon": 120,
	"leavanny": 45,
	"venipede": 255,
	"whirlipede": 120,
	"scolipede": 45,
	"cottonee": 190,
	"whimsicott": 75,
	"petilil": 190,
	"lilligant": 75,
	"basculinredstriped": 25,
	"sandile": 180,
	"krokorok": 90,
	"krookodile": 45,
	"darumaka": 120,
	"darmanitan": 60,
	"maractus": 255,
	"dwebble": 190,
	"crustle": 75,
	"scraggy": 180,
	"scrafty": 90,
	"sigilyph": 45,
	"yamask": 190,
	"cofagrigus": 90,
	"tirtouga": 45,
	"carracosta": 45,
	"archen": 45,
	"archeops": 45,
	"trubbish": 190,
	"garbodor": 60,
	"zorua": 75,
	"zoroark": 45,
	"minccino": 255,
	"cinccino": 60,
	"gothita": 200,
	"gothorita": 100,
	"gothitelle": 50,
	"solosis": 200,
	"duosion": 100,
	"reuniclus": 50,
	"ducklett": 190,
	"swanna": 45,
	"vanillite": 255,
	"vanillish": 120,
	"vanilluxe": 45,
	"deerling": 190,
	"sawsbuck": 75,
	"emolga": 200,
	"karrablast": 200,
	"escavalier": 75,
	"foongus": 190,
	"amoonguss": 75,
	"frillish": 190,
	"jellicent": 60,
	"alomomola": 75,
	"joltik": 190,
	"galvantula": 75,
	"ferroseed": 255,
	"ferrothorn": 90,
	"klink": 130,
	"klang": 60,
	"klinklang": 30,
	"tynamo": 190,
	"eelektrik": 60,
	"eelektross": 30,
	"elgyem": 255,
	"beheeyem": 90,
	"litwick": 190,
	"lampent": 90,
	"chandelure": 45,
	"axew": 75,
	"fraxure": 60,
	"haxorus": 45,
	"cubchoo": 120,
	"beartic": 60,
	"cryogonal": 25,
	"shelmet": 200,
	"accelgor": 75,
	"stunfisk": 75,
	"mienfoo": 180,
	"mienshao": 45,
	"druddigon": 45,
	"golett": 190,
	"golurk": 90,
	"pawniard": 120,
	"bisharp": 45,
	"bouffalant": 45,
	"rufflet": 190,
	"braviary": 60,
	"vullaby": 190,
	"mandibuzz": 60,
	"heatmor": 90,
	"durant": 90,
	"deino": 45,
	"zweilous": 45,
	"hydreigon": 45,
	"larvesta": 45,
	"volcarona": 15,
	"cobalion": 3,
	"terrakion": 3,
	"virizion": 3,
	"tornadus": 3,
	"thundurus": 3,
	"reshiram": 3,
	"zekrom": 3,
	"landorus": 3,
	"kyurem": 3,
	"keldeo": 3,
	"meloetta": 3,
	"genesect": 3,
	"chespin": 45,
	"quilladin": 45,
	"chesnaught": 45,
	"fennekin": 45,
	"braixen": 45,
	"delphox": 45,
	"froakie": 45,
	"frogadier": 45,
	"greninja": 45,
	"bunnelby": 255,
	"diggersby": 127,
	"fletchling": 255,
	"fletchinder": 120,
	"talonflame": 45,
	"scatterbug": 255,
	"spewpa": 120,
	"vivillon": 45,
	"litleo": 220,
	"pyroar": 65,
	"flabebe": 225,
	"floette": 120,
	"florges": 45,
	"skiddo": 200,
	"gogoat": 45,
	"pancham": 220,
	"pangoro": 65,
	"furfrou": 160,
	"espurr": 190,
	"meowstic": 75,
	"honedge": 180,
	"doublade": 90,
	"aegislash": 45,
	"spritzee": 200,
	"aromatisse": 140,
	"swirlix": 200,
	"slurpuff": 140,
	"inkay": 190,
	"malamar": 80,
	"binacle": 120,
	"barbaracle": 45,
	"skrelp": 225,
	"dragalge": 55,
	"clauncher": 225,
	"clawitzer": 55,
	"helioptile": 190,
	"heliolisk": 75,
	"tyrunt": 45,
	"tyrantrum": 45,
	"amaura": 45,
	"aurorus": 45,
	"sylveon": 45,
	"hawlucha": 100,
	"dedenne": 180,
	"carbink": 60,
	"goomy": 45,
	"sliggoo": 45,
	"goodra": 45,
	"klefki": 75,
	"phantump": 120,
	"trevenant": 60,
	"pumpkaboo": 120,
	"gourgeist": 60,
	"bergmite": 190,
	"avalugg": 55,
	"noibat": 190,
	"noivern": 45,
	"xerneas": 45,
	"yveltal": 45,
	"zygarde50": 3,
	"diancie": 3,
	"hoopa": 3,
	"volcanion": 3,
	"rowlet": 45,
	"dartrix": 45,
	"decidueye": 45,
	"litten": 45,
	"torracat": 45,
	"incineroar": 45,
	"popplio": 45,
	"brionne": 45,
	"primarina": 45,
	"pikipek": 255,
	"trumbeak": 120,
	"toucannon": 45,
	"yungoos": 255,
	"gumshoos": 127,
	"grubbin": 255,
	"charjabug": 120,
	"vikavolt": 45,
	"crabrawler": 225,
	"crabominable": 60,
	"oricorio": 45,
	"cutiefly": 190,
	"ribombee": 75,
	"rockruff": 190,
	"lycanroc": 90,
	"wishiwashi": 60,
	"mareanie": 190,
	"toxapex": 75,
	"mudbray": 190,
	"mudsdale": 60,
	"dewpider": 200,
	"araquanid": 100,
	"fomantis": 190,
	"lurantis": 75,
	"morelull": 190,
	"shiinotic": 75,
	"salandit": 120,
	"salazzle": 45,
	"stufful": 140,
	"bewear": 70,
	"bounsweet": 235,
	"steenee": 120,
	"tsareena": 45,
	"comfey": 60,
	"oranguru": 45,
	"passimian": 45,
	"wimpod": 90,
	"golisopod": 45,
	"sandygast": 140,
	"palossand": 60,
	"pyukumuku": 60,
	"typenull": 3,
	"silvally": 3,
	"minior": 30,
	"komala": 45,
	"turtonator": 70,
	"togedemaru": 180,
	"mimikyu": 45,
	"bruxish": 80,
	"drampa": 70,
	"dhelmise": 25,
	"jangmoo": 45,
	"hakamoo": 45,
	"kommoo": 45,
	"tapukoko": 3,
	"tapulele": 3,
	"tapubulu": 3,
	"tapufini": 3,
	"cosmog": 45,
	"cosmoem": 45,
	"solgaleo": 45,
	"lunala": 45,
	"nihilego": 45,
	"buzzwole": 45,
	"pheromosa": 45,
	"xurkitree": 45,
	"celesteela": 45,
	"kartana": 45,
	"guzzlord": 45,
	"necrozma": 255,
	"magearna": 3,
	"marshadow": 3,
	"poipole": 45,
	"naganadel": 45,
	"stakataka": 30,
	"blacephalon": 30,
	"zeraora": 3,
	"meltan": 3,
	"melmetal": 3,
	"grookey": 45,
	"thwackey": 45,
	"rillaboom": 45,
	"scorbunny": 45,
	"raboot": 45,
	"cinderace": 45,
	"sobble": 45,
	"drizzile": 45,
	"inteleon": 45,
	"skwovet": 255,
	"greedent": 90,
	"rookidee": 255,
	"corvisquire": 120,
	"corviknight": 45,
	"blipbug": 255,
	"dottler": 120,
	"orbeetle": 45,
	"nickit": 255,
	"thievul": 127,
	"gossifleur": 190,
	"eldegoss": 75,
	"wooloo": 255,
	"dubwool": 127,
	"chewtle": 255,
	"drednaw": 75,
	"yamper": 255,
	"boltund": 45,
	"rolycoly": 255,
	"carkol": 120,
	"coalossal": 45,
	"applin": 255,
	"flapple": 45,
	"appletun": 45,
	"silicobra": 255,
	"sandaconda": 120,
	"cramorant": 45,
	"arrokuda": 255,
	"barraskewda": 60,
	"toxel": 75,
	"toxtricity": 45,
	"sizzlipede": 190,
	"centiskorch": 75,
	"clobbopus": 180,
	"grapploct": 45,
	"sinistea": 120,
	"polteageist": 60,
	"hatenna": 235,
	"hattrem": 120,
	"hatterene": 45,
	"impidimp": 255,
	"morgrem": 120,
	"grimmsnarl": 45,
	"obstagoon": 45,
	"perrserker": 90,
	"cursola": 30,
	"sirfetchd": 45,
	"mrrime": 45,
	"runerigus": 90,
	"milcery": 200,
	"alcremie": 100,
	"falinks": 45,
	"pincurchin": 75,
	"snom": 190,
	"frosmoth": 75,
	"stonjourner": 60,
	"eiscue": 60,
	"indeedee": 30,
	"morpeko": 180,
	"cufant": 190,
	"copperajah": 90,
	"dracozolt": 45,
	"arctozolt": 45,
	"dracovish": 45,
	"arctovish": 45,
	"duraludon": 45,
	"dreepy": 45,
	"drakloak": 45,
	"dragapult": 45,
	"zacian": 10,
	"zamazenta": 10,
	"eternatus": 255,
	"kubfu": 3,
	"urshifu": 3,
	"zarude": 3,
	"regieleki": 3,
	"regidrago": 3,
	"glastrier": 3,
	"spectrier": 3,
	"calyrex": 3,
	"wyrdeer": 135,
	"kleavor": 115,
	"ursaluna": 75,
	"basculegion": 135,
	"sneasler": 135,
	"overqwil": 135,
	"enamorus": 3,
	"sprigatito": 45,
	"floragato": 45,
	"meowscarada": 45,
	"fuecoco": 45,
	"crocalor": 45,
	"skeledirge": 45,
	"quaxly": 45,
	"quaxwell": 45,
	"quaquaval": 45,
	"lechonk": 255,
	"oinkologne": 100,
	"tarountula": 255,
	"spidops": 120,
	"nymble": 190,
	"lokix": 30,
	"pawmi": 190,
	"pawmo": 80,
	"pawmot": 45,
	"tandemaus": 150,
	"mausholdfamilyoffour": 75,
	"fidough": 190,
	"dachsbun": 90,
	"smoliv": 255,
	"dolliv": 120,
	"arboliva": 45,
	"squawkabillygreenplumage": 190,
	"nacli": 255,
	"naclstack": 120,
	"garganacl": 45,
	"charcadet": 90,
	"armarouge": 25,
	"ceruledge": 25,
	"tadbulb": 190,
	"bellibolt": 50,
	"wattrel": 180,
	"kilowattrel": 90,
	"maschiff": 150,
	"mabosstiff": 75,
	"shroodle": 190,
	"grafaiai": 90,
	"bramblin": 190,
	"brambleghast": 45,
	"toedscool": 190,
	"toedscruel": 90,
	"klawf": 120,
	"capsakid": 190,
	"scovillain": 75,
	"rellor": 190,
	"rabsca": 45,
	"flittle": 120,
	"espathra": 60,
	"tinkatink": 190,
	"tinkatuff": 90,
	"tinkaton": 45,
	"wiglett": 255,
	"wugtrio": 50,
	"bombirdier": 25,
	"finizen": 200,
	"palafinzero": 45,
	"varoom": 190,
	"revavroom": 75,
	"cyclizar": 190,
	"orthworm": 25,
	"glimmet": 70,
	"glimmora": 25,
	"greavard": 120,
	"houndstone": 60,
	"flamigo": 100,
	"cetoddle": 150,
	"cetitan": 50,
	"veluza": 100,
	"dondozo": 25,
	"tatsugiricurly": 100,
	"annihilape": 45,
	"clodsire": 90,
	"farigiraf": 45,
	"dudunsparcetwosegment": 45,
	"kingambit": 25,
	"greattusk": 30,
	"screamtail": 50,
	"brutebonnet": 50,
	"fluttermane": 30,
	"slitherwing": 30,
	"sandyshocks": 30,
	"irontreads": 30,
	"ironbundle": 50,
	"ironhands": 50,
	"ironjugulis": 30,
	"ironmoth": 30,
	"ironthorns": 30,
	"frigibax": 45,
	"arctibax": 25,
	"baxcalibur": 10,
	"gimmighoul": 45,
	"gholdengo": 45,
	"wochien": 6,
	"chienpao": 6,
	"tinglu": 6,
	"chiyu": 6,
	"roaringmoon": 10,
	"ironvaliant": 10,
	"koraidon": 3,
	"miraidon": 3,
	"walkingwake": 5,
	"ironleaves": 5,
	"dipplin": 45,
	"poltchageist": 120,
	"sinistcha": 60,
	"okidogi": 3,
	"munkidori": 3,
	"fezandipiti": 3,
	"ogerpon": 5,
	"archaludon": 10,
	"hydrapple": 10,
	"gougingfire": 10,
	"ragingbolt": 10,
	"ironboulder": 10,
	"ironcrown": 10,
	"terapagos": 255,
	"pecharunt": 3,
	"deoxysattack": 3,
	"deoxysdefense": 3,
	"deoxysspeed": 3,
	"wormadamsandy": 45,
	"wormadamtrash": 45,
	"shayminsky": 45,
	"giratinaorigin": 3,
	"rotomheat": 45,
	"rotomwash": 45,
	"rotomfrost": 45,
	"rotomfan": 45,
	"rotommow": 45,
	"castformsunny": 45,
	"castformrainy": 45,
	"castformsnowy": 45,
	"basculinbluestriped": 25,
	"darmanitanzen": 60,
	"meloettapirouette": 3,
	"tornadustherian": 3,
	"thundurustherian": 3,
	"landorustherian": 3,
	"kyuremblack": 3,
	"kyuremwhite": 3,
	"keldeoresolute": 3,
	"meowsticfe": 75,
	"aegislashblade": 45,
	"pumpkaboosmall": 120,
	"pumpkaboolarge": 120,
	"pumpkaboosuper": 120,
	"gourgeistsmall": 60,
	"gourgeistlarge": 60,
	"gourgeistsuper": 60,
	"venusaurmega": 45,
	"charizardmegax": 45,
	"charizardmegay": 45,
	"blastoisemega": 45,
	"alakazammega": 50,
	"gengarmega": 45,
	"kangaskhanmega": 45,
	"pinsirmega": 45,
	"gyaradosmega": 45,
	"aerodactylmega": 45,
	"mewtwomegax": 3,
	"mewtwomegay": 3,
	"ampharosmega": 45,
	"scizormega": 25,
	"heracrossmega": 45,
	"houndoommega": 45,
	"tyranitarmega": 45,
	"blazikenmega": 45,
	"gardevoirmega": 45,
	"mawilemega": 45,
	"aggronmega": 45,
	"medichammega": 90,
	"manectricmega": 45,
	"banettemega": 45,
	"absolmega": 30,
	"garchompmega": 45,
	"lucariomega": 45,
	"abomasnowmega": 60,
	"floetteeternal": 120,
	"latiasmega": 3,
	"latiosmega": 3,
	"swampertmega": 45,
	"sceptilemega": 45,
	"sableyemega": 45,
	"altariamega": 45,
	"gallademega": 45,
	"audinomega": 255,
	"sharpedomega": 60,
	"slowbromega": 75,
	"steelixmega": 25,
	"pidgeotmega": 45,
	"glaliemega": 75,
	"dianciemega": 3,
	"metagrossmega": 3,
	"kyogreprimal": 3,
	"groudonprimal": 3,
	"rayquazamega": 45,
	"pikachurockstar": 190,
	"pikachubelle": 190,
	"pikachupopstar": 190,
	"pikachuphd": 190,
	"pikachulibre": 190,
	"pikachucosplay": 190,
	"hoopaunbound": 3,
	"cameruptmega": 150,
	"lopunnymega": 60,
	"salamencemega": 45,
	"beedrillmega": 45,
	"rattataalola": 255,
	"raticatealola": 127,
	"raticatetotemalola": 127,
	"pikachuoriginalcap": 190,
	"pikachuhoenncap": 190,
	"pikachusinnohcap": 190,
	"pikachuunovacap": 190,
	"pikachukaloscap": 190,
	"pikachualolacap": 190,
	"raichualola": 75,
	"sandshrewalola": 255,
	"sandslashalola": 90,
	"vulpixalola": 190,
	"ninetalesalola": 75,
	"diglettalola": 255,
	"dugtrioalola": 50,
	"meowthalola": 255,
	"persianalola": 90,
	"geodudealola": 255,
	"graveleralola": 120,
	"golemalola": 45,
	"grimeralola": 190,
	"mukalola": 75,
	"exeggutoralola": 45,
	"marowakalola": 75,
	"greninjabattlebond": 45,
	"greninjaash": 45,
	"zygarde10powerconstruct": 3,
	"zygarde50powerconstruct": 3,
	"zygardecomplete": 3,
	"gumshoostotem": 127,
	"vikavolttotem": 45,
	"oricoriopompom": 45,
	"oricoriopau": 45,
	"oricoriosensu": 45,
	"lycanrocmidnight": 90,
	"wishiwashischool": 60,
	"lurantistotem": 75,
	"salazzletotem": 45,
	"miniororangemeteor": 30,
	"minioryellowmeteor": 30,
	"miniorgreenmeteor": 30,
	"miniorbluemeteor": 30,
	"miniorindigometeor": 30,
	"miniorvioletmeteor": 30,
	"miniorred": 30,
	"miniororange": 30,
	"minioryellow": 30,
	"miniorgreen": 30,
	"miniorblue": 30,
	"miniorindigo": 30,
	"miniorviolet": 30,
	"mimikyubusted": 45,
	"mimikyutotem": 45,
	"mimikyutotembusted": 45,
	"kommoototem": 45,
	"magearnaoriginal": 3,
	"pikachupartnercap": 190,
	"marowaktotem": 75,
	"ribombeetotem": 75,
	"rockruffowntempo": 190,
	"lycanrocdusk": 90,
	"araquanidtotem": 100,
	"togedemarutotem": 180,
	"necrozmadusk": 255,
	"necrozmadawn": 255,
	"necrozmaultra": 255,
	"pikachustarter": 190,
	"eeveestarter": 45,
	"pikachuworldcap": 190,
	"meowthgalar": 255,
	"ponytagalar": 190,
	"rapidashgalar": 60,
	"slowpokegalar": 190,
	"slowbrogalar": 75,
	"farfetchdgalar": 45,
	"weezinggalar": 60,
	"mrmimegalar": 45,
	"articunogalar": 3,
	"zapdosgalar": 3,
	"moltresgalar": 3,
	"slowkinggalar": 70,
	"corsolagalar": 60,
	"zigzagoongalar": 255,
	"linoonegalar": 90,
	"darumakagalar": 120,
	"darmanitangalar": 60,
	"darmanitangalarzen": 60,
	"yamaskgalar": 190,
	"stunfiskgalar": 75,
	"zygarde10": 3,
	"cramorantgulping": 45,
	"cramorantgorging": 45,
	"toxtricitylowkey": 45,
	"eiscueno": 60,
	"indeedeefe": 30,
	"morpekohangry": 180,
	"zaciancrowned": 10,
	"zamazentacrowned": 10,
	"eternatuseternamax": 255,
	"urshifurapidstrike": 3,
	"zarudedada": 3,
	"calyrexshadow": 3,
	"venusaurgmax": 45,
	"charizardgmax": 45,
	"blastoisegmax": 45,
	"butterfreegmax": 45,
	"pikachugmax": 190,
	"meowthgmax": 255,
	"machampgmax": 45,
	"gengargmax": 45,
	"kinglergmax": 60,
	"laprasgmax": 45,
	"eeveegmax": 45,
	"snorlaxgmax": 25,
	"garbodorgmax": 60,
	"melmetalgmax": 3,
	"rillaboomgmax": 45,
	"cinderacegmax": 45,
	"inteleongmax": 45,
	"corviknightgmax": 45,
	"orbeetlegmax": 45,
	"drednawgmax": 75,
	"coalossalgmax": 45,
	"flapplegmax": 45,
	"appletungmax": 45,
	"sandacondagmax": 120,
	"toxtricityampedgmax": 45,
	"centiskorchgmax": 75,
	"hatterenegmax": 45,
	"grimmsnarlgmax": 45,
	"alcremiegmax": 100,
	"copperajahgmax": 90,
	"duraludongmax": 45,
	"urshifusinglestrikegmax": 3,
	"urshifurapidstrikegmax": 3,
	"toxtricitylowkeygmax": 45,
	"growlithehisui": 190,
	"arcaninehisui": 75,
	"voltorbhisui": 190,
	"electrodehisui": 60,
	"typhlosionhisui": 45,
	"qwilfishhisui": 45,
	"sneaselhisui": 60,
	"samurotthisui": 45,
	"lilliganthisui": 75,
	"zoruahisui": 75,
	"zoroarkhisui": 45,
	"braviaryhisui": 60,
	"sliggoohisui": 45,
	"goodrahisui": 45,
	"avalugghisui": 55,
	"decidueyehisui": 45,
	"dialgaorigin": 3,
	"palkiaorigin": 3,
	"basculinwhitestriped": 25,
	"basculegionfe": 135,
	"enamorustherian": 3,
	"taurospaldeacombatbreed": 45,
	"taurospaldeablazebreed": 45,
	"taurospaldeaaquabreed": 45,
	"wooperpaldea": 255,
	"oinkolognefe": 100,
	"dudunsparcethreesegment": 45,
	"palafinhero": 45,
	"mausholdfamilyofthree": 75,
	"tatsugiridroopy": 100,
	"tatsugiristretchy": 100,
	"squawkabillyblueplumage": 190,
	"squawkabillyyellowplumage": 190,
	"squawkabillywhiteplumage": 190,
	"gimmighoulroaming": 45,
	"koraidonlimitedbuild": 3,
	"koraidonsprintingbuild": 3,
	"koraidonswimmingbuild": 3,
	"koraidonglidingbuild": 3,
	"miraidonlowpowermode": 3,
	"miraidondrivemode": 3,
	"miraidonaquaticmode": 3,
	"miraidonglidemode": 3,
	"ursalunabloodmoon": 75,
	"ogerponwellspringmask": 5,
	"ogerponhearthflamemask": 5,
	"ogerponcornerstonemask": 5,
	"terapagosterastal": 255,
	"terapagosstellar": 255,
};

export const GROWTH_RATES: Record<string, string> = {
	"bulbasaur": "Medium Slow",
	"ivysaur": "Medium Slow",
	"venusaur": "Medium Slow",
	"charmander": "Medium Slow",
	"charmeleon": "Medium Slow",
	"charizard": "Medium Slow",
	"squirtle": "Medium Slow",
	"wartortle": "Medium Slow",
	"blastoise": "Medium Slow",
	"caterpie": "Medium Fast",
	"metapod": "Medium Fast",
	"butterfree": "Medium Fast",
	"weedle": "Medium Fast",
	"kakuna": "Medium Fast",
	"beedrill": "Medium Fast",
	"pidgey": "Medium Slow",
	"pidgeotto": "Medium Slow",
	"pidgeot": "Medium Slow",
	"rattata": "Medium Fast",
	"raticate": "Medium Fast",
	"spearow": "Medium Fast",
	"fearow": "Medium Fast",
	"ekans": "Medium Fast",
	"arbok": "Medium Fast",
	"pikachu": "Medium Fast",
	"raichu": "Medium Fast",
	"sandshrew": "Medium Fast",
	"sandslash": "Medium Fast",
	"nidoranf": "Medium Slow",
	"nidorina": "Medium Slow",
	"nidoqueen": "Medium Slow",
	"nidoranm": "Medium Slow",
	"nidorino": "Medium Slow",
	"nidoking": "Medium Slow",
	"clefairy": "Fast",
	"clefable": "Fast",
	"vulpix": "Medium Fast",
	"ninetales": "Medium Fast",
	"jigglypuff": "Fast",
	"wigglytuff": "Fast",
	"zubat": "Medium Fast",
	"golbat": "Medium Fast",
	"oddish": "Medium Slow",
	"gloom": "Medium Slow",
	"vileplume": "Medium Slow",
	"paras": "Medium Fast",
	"parasect": "Medium Fast",
	"venonat": "Medium Fast",
	"venomoth": "Medium Fast",
	"diglett": "Medium Fast",
	"dugtrio": "Medium Fast",
	"meowth": "Medium Fast",
	"persian": "Medium Fast",
	"psyduck": "Medium Fast",
	"golduck": "Medium Fast",
	"mankey": "Medium Fast",
	"primeape": "Medium Fast",
	"growlithe": "Slow",
	"arcanine": "Slow",
	"poliwag": "Medium Slow",
	"poliwhirl": "Medium Slow",
	"poliwrath": "Medium Slow",
	"abra": "Medium Slow",
	"kadabra": "Medium Slow",
	"alakazam": "Medium Slow",
	"machop": "Medium Slow",
	"machoke": "Medium Slow",
	"machamp": "Medium Slow",
	"bellsprout": "Medium Slow",
	"weepinbell": "Medium Slow",
	"victreebel": "Medium Slow",
	"tentacool": "Slow",
	"tentacruel": "Slow",
	"geodude": "Medium Slow",
	"graveler": "Medium Slow",
	"golem": "Medium Slow",
	"ponyta": "Medium Fast",
	"rapidash": "Medium Fast",
	"slowpoke": "Medium Fast",
	"slowbro": "Medium Fast",
	"magnemite": "Medium Fast",
	"magneton": "Medium Fast",
	"farfetchd": "Medium Fast",
	"doduo": "Medium Fast",
	"dodrio": "Medium Fast",
	"seel": "Medium Fast",
	"dewgong": "Medium Fast",
	"grimer": "Medium Fast",
	"muk": "Medium Fast",
	"shellder": "Slow",
	"cloyster": "Slow",
	"gastly": "Medium Slow",
	"haunter": "Medium Slow",
	"gengar": "Medium Slow",
	"onix": "Medium Fast",
	"drowzee": "Medium Fast",
	"hypno": "Medium Fast",
	"krabby": "Medium Fast",
	"kingler": "Medium Fast",
	"voltorb": "Medium Fast",
	"electrode": "Medium Fast",
	"exeggcute": "Slow",
	"exeggutor": "Slow",
	"cubone": "Medium Fast",
	"marowak": "Medium Fast",
	"hitmonlee": "Medium Fast",
	"hitmonchan": "Medium Fast",
	"lickitung": "Medium Fast",
	"koffing": "Medium Fast",
	"weezing": "Medium Fast",
	"rhyhorn": "Slow",
	"rhydon": "Slow",
	"chansey": "Fast",
	"tangela": "Medium Fast",
	"kangaskhan": "Medium Fast",
	"horsea": "Medium Fast",
	"seadra": "Medium Fast",
	"goldeen": "Medium Fast",
	"seaking": "Medium Fast",
	"staryu": "Slow",
	"starmie": "Slow",
	"mrmime": "Medium Fast",
	"scyther": "Medium Fast",
	"jynx": "Medium Fast",
	"electabuzz": "Medium Fast",
	"magmar": "Medium Fast",
	"pinsir": "Slow",
	"tauros": "Slow",
	"magikarp": "Slow",
	"gyarados": "Slow",
	"lapras": "Slow",
	"ditto": "Medium Fast",
	"eevee": "Medium Fast",
	"vaporeon": "Medium Fast",
	"jolteon": "Medium Fast",
	"flareon": "Medium Fast",
	"porygon": "Medium Fast",
	"omanyte": "Medium Fast",
	"omastar": "Medium Fast",
	"kabuto": "Medium Fast",
	"kabutops": "Medium Fast",
	"aerodactyl": "Slow",
	"snorlax": "Slow",
	"articuno": "Slow",
	"zapdos": "Slow",
	"moltres": "Slow",
	"dratini": "Slow",
	"dragonair": "Slow",
	"dragonite": "Slow",
	"mewtwo": "Slow",
	"mew": "Medium Slow",
	"chikorita": "Medium Slow",
	"bayleef": "Medium Slow",
	"meganium": "Medium Slow",
	"cyndaquil": "Medium Slow",
	"quilava": "Medium Slow",
	"typhlosion": "Medium Slow",
	"totodile": "Medium Slow",
	"croconaw": "Medium Slow",
	"feraligatr": "Medium Slow",
	"sentret": "Medium Fast",
	"furret": "Medium Fast",
	"hoothoot": "Medium Fast",
	"noctowl": "Medium Fast",
	"ledyba": "Fast",
	"ledian": "Fast",
	"spinarak": "Fast",
	"ariados": "Fast",
	"crobat": "Medium Fast",
	"chinchou": "Slow",
	"lanturn": "Slow",
	"pichu": "Medium Fast",
	"cleffa": "Fast",
	"igglybuff": "Fast",
	"togepi": "Fast",
	"togetic": "Fast",
	"natu": "Medium Fast",
	"xatu": "Medium Fast",
	"mareep": "Medium Slow",
	"flaaffy": "Medium Slow",
	"ampharos": "Medium Slow",
	"bellossom": "Medium Slow",
	"marill": "Fast",
	"azumarill": "Fast",
	"sudowoodo": "Medium Fast",
	"politoed": "Medium Slow",
	"hoppip": "Medium Slow",
	"skiploom": "Medium Slow",
	"jumpluff": "Medium Slow",
	"aipom": "Fast",
	"sunkern": "Medium Slow",
	"sunflora": "Medium Slow",
	"yanma": "Medium Fast",
	"wooper": "Medium Fast",
	"quagsire": "Medium Fast",
	"espeon": "Medium Fast",
	"umbreon": "Medium Fast",
	"murkrow": "Medium Slow",
	"slowking": "Medium Fast",
	"misdreavus": "Fast",
	"unown": "Medium Fast",
	"wobbuffet": "Medium Fast",
	"girafarig": "Medium Fast",
	"pineco": "Medium Fast",
	"forretress": "Medium Fast",
	"dunsparce": "Medium Fast",
	"gligar": "Medium Slow",
	"steelix": "Medium Fast",
	"snubbull": "Fast",
	"granbull": "Fast",
	"qwilfish": "Medium Fast",
	"scizor": "Medium Fast",
	"shuckle": "Medium Slow",
	"heracross": "Slow",
	"sneasel": "Medium Slow",
	"teddiursa": "Medium Fast",
	"ursaring": "Medium Fast",
	"slugma": "Medium Fast",
	"magcargo": "Medium Fast",
	"swinub": "Slow",
	"piloswine": "Slow",
	"corsola": "Fast",
	"remoraid": "Medium Fast",
	"octillery": "Medium Fast",
	"delibird": "Fast",
	"mantine": "Slow",
	"skarmory": "Slow",
	"houndour": "Slow",
	"houndoom": "Slow",
	"kingdra": "Medium Fast",
	"phanpy": "Medium Fast",
	"donphan": "Medium Fast",
	"porygon2": "Medium Fast",
	"stantler": "Slow",
	"smeargle": "Fast",
	"tyrogue": "Medium Fast",
	"hitmontop": "Medium Fast",
	"smoochum": "Medium Fast",
	"elekid": "Medium Fast",
	"magby": "Medium Fast",
	"miltank": "Slow",
	"blissey": "Fast",
	"raikou": "Slow",
	"entei": "Slow",
	"suicune": "Slow",
	"larvitar": "Slow",
	"pupitar": "Slow",
	"tyranitar": "Slow",
	"lugia": "Slow",
	"hooh": "Slow",
	"celebi": "Medium Slow",
	"treecko": "Medium Slow",
	"grovyle": "Medium Slow",
	"sceptile": "Medium Slow",
	"torchic": "Medium Slow",
	"combusken": "Medium Slow",
	"blaziken": "Medium Slow",
	"mudkip": "Medium Slow",
	"marshtomp": "Medium Slow",
	"swampert": "Medium Slow",
	"poochyena": "Medium Fast",
	"mightyena": "Medium Fast",
	"zigzagoon": "Medium Fast",
	"linoone": "Medium Fast",
	"wurmple": "Medium Fast",
	"silcoon": "Medium Fast",
	"beautifly": "Medium Fast",
	"cascoon": "Medium Fast",
	"dustox": "Medium Fast",
	"lotad": "Medium Slow",
	"lombre": "Medium Slow",
	"ludicolo": "Medium Slow",
	"seedot": "Medium Slow",
	"nuzleaf": "Medium Slow",
	"shiftry": "Medium Slow",
	"taillow": "Medium Slow",
	"swellow": "Medium Slow",
	"wingull": "Medium Fast",
	"pelipper": "Medium Fast",
	"ralts": "Slow",
	"kirlia": "Slow",
	"gardevoir": "Slow",
	"surskit": "Medium Fast",
	"masquerain": "Medium Fast",
	"shroomish": "Fluctuating",
	"breloom": "Fluctuating",
	"slakoth": "Slow",
	"vigoroth": "Slow",
	"slaking": "Slow",
	"nincada": "Erratic",
	"ninjask": "Erratic",
	"shedinja": "Erratic",
	"whismur": "Medium Slow",
	"loudred": "Medium Slow",
	"exploud": "Medium Slow",
	"makuhita": "Fluctuating",
	"hariyama": "Fluctuating",
	"azurill": "Fast",
	"nosepass": "Medium Fast",
	"skitty": "Fast",
	"delcatty": "Fast",
	"sableye": "Medium Slow",
	"mawile": "Fast",
	"aron": "Slow",
	"lairon": "Slow",
	"aggron": "Slow",
	"meditite": "Medium Fast",
	"medicham": "Medium Fast",
	"electrike": "Slow",
	"manectric": "Slow",
	"plusle": "Medium Fast",
	"minun": "Medium Fast",
	"volbeat": "Erratic",
	"illumise": "Fluctuating",
	"roselia": "Medium Slow",
	"gulpin": "Fluctuating",
	"swalot": "Fluctuating",
	"carvanha": "Slow",
	"sharpedo": "Slow",
	"wailmer": "Fluctuating",
	"wailord": "Fluctuating",
	"numel": "Medium Fast",
	"camerupt": "Medium Fast",
	"torkoal": "Medium Fast",
	"spoink": "Fast",
	"grumpig": "Fast",
	"spinda": "Fast",
	"trapinch": "Medium Slow",
	"vibrava": "Medium Slow",
	"flygon": "Medium Slow",
	"cacnea": "Medium Slow",
	"cacturne": "Medium Slow",
	"swablu": "Erratic",
	"alt": "Erratic",
	"zangoose": "Erratic",
	"seviper": "Fluctuating",
	"lunatone": "Fast",
	"solrock": "Fast",
	"barboach": "Medium Fast",
	"whiscash": "Medium Fast",
	"corphish": "Fluctuating",
	"crawdaunt": "Fluctuating",
	"baltoy": "Medium Fast",
	"claydol": "Medium Fast",
	"lileep": "Erratic",
	"cradily": "Erratic",
	"anorith": "Erratic",
	"armaldo": "Erratic",
	"feebas": "Erratic",
	"milotic": "Erratic",
	"castform": "Medium Fast",
	"kecleon": "Medium Slow",
	"shuppet": "Fast",
	"banette": "Fast",
	"duskull": "Fast",
	"dusclops": "Fast",
	"tropius": "Slow",
	"chimecho": "Fast",
	"absol": "Medium Slow",
	"wynaut": "Medium Fast",
	"snorunt": "Medium Fast",
	"glalie": "Medium Fast",
	"spheal": "Medium Slow",
	"sealeo": "Medium Slow",
	"walrein": "Medium Slow",
	"clamperl": "Erratic",
	"huntail": "Erratic",
	"gorebyss": "Erratic",
	"relicanth": "Slow",
	"luvdisc": "Fast",
	"bagon": "Slow",
	"shelgon": "Slow",
	"salamence": "Slow",
	"beldum": "Slow",
	"metang": "Slow",
	"metagross": "Slow",
	"regirock": "Slow",
	"reg": "Slow",
	"registeel": "Slow",
	"latias": "Slow",
	"latios": "Slow",
	"kyogre": "Slow",
	"groudon": "Slow",
	"rayquaza": "Slow",
	"jirachi": "Slow",
	"deoxys": "Slow",
	"turtwig": "Medium Slow",
	"grotle": "Medium Slow",
	"torterra": "Medium Slow",
	"chimchar": "Medium Slow",
	"monferno": "Medium Slow",
	"infernape": "Medium Slow",
	"piplup": "Medium Slow",
	"prinplup": "Medium Slow",
	"empoleon": "Medium Slow",
	"starly": "Medium Slow",
	"staravia": "Medium Slow",
	"staraptor": "Medium Slow",
	"bidoof": "Medium Fast",
	"bibarel": "Medium Fast",
	"kricketot": "Medium Slow",
	"kricketune": "Medium Slow",
	"shinx": "Medium Slow",
	"luxio": "Medium Slow",
	"luxray": "Medium Slow",
	"budew": "Medium Slow",
	"roserade": "Medium Slow",
	"cranidos": "Erratic",
	"rampardos": "Erratic",
	"shieldon": "Erratic",
	"bastiodon": "Erratic",
	"burmy": "Medium Fast",
	"wormadamplant": "Medium Fast",
	"mothim": "Medium Fast",
	"combee": "Medium Slow",
	"vespiquen": "Medium Slow",
	"pachirisu": "Medium Fast",
	"buizel": "Medium Fast",
	"floatzel": "Medium Fast",
	"cherubi": "Medium Fast",
	"cherrim": "Medium Fast",
	"shellos": "Medium Fast",
	"gastrodon": "Medium Fast",
	"ambipom": "Fast",
	"drifloon": "Fluctuating",
	"drifblim": "Fluctuating",
	"buneary": "Medium Fast",
	"lopunny": "Medium Fast",
	"mismagius": "Fast",
	"honchkrow": "Medium Slow",
	"glameow": "Fast",
	"purugly": "Fast",
	"chingling": "Fast",
	"stunky": "Medium Fast",
	"skuntank": "Medium Fast",
	"bronzor": "Medium Fast",
	"bronzong": "Medium Fast",
	"bonsly": "Medium Fast",
	"mimejr": "Medium Fast",
	"happiny": "Fast",
	"chatot": "Medium Slow",
	"spiritomb": "Medium Fast",
	"gible": "Slow",
	"gabite": "Slow",
	"garchomp": "Slow",
	"munchlax": "Slow",
	"riolu": "Medium Slow",
	"lucario": "Medium Slow",
	"hippopotas": "Slow",
	"hippowdon": "Slow",
	"skorupi": "Slow",
	"drapion": "Slow",
	"croagunk": "Medium Fast",
	"toxicroak": "Medium Fast",
	"carnivine": "Slow",
	"finneon": "Erratic",
	"lumineon": "Erratic",
	"mantyke": "Slow",
	"snover": "Slow",
	"abomasnow": "Slow",
	"weavile": "Medium Slow",
	"magnezone": "Medium Fast",
	"lickilicky": "Medium Fast",
	"rhyperior": "Slow",
	"tangrowth": "Medium Fast",
	"electivire": "Medium Fast",
	"magmortar": "Medium Fast",
	"togekiss": "Fast",
	"yanmega": "Medium Fast",
	"leafeon": "Medium Fast",
	"glaceon": "Medium Fast",
	"gliscor": "Medium Slow",
	"mamoswine": "Slow",
	"porygonz": "Medium Fast",
	"gallade": "Slow",
	"probopass": "Medium Fast",
	"dusknoir": "Fast",
	"froslass": "Medium Fast",
	"rotom": "Medium Fast",
	"uxie": "Slow",
	"mesprit": "Slow",
	"azelf": "Slow",
	"dialga": "Slow",
	"palkia": "Slow",
	"heatran": "Slow",
	"regigigas": "Slow",
	"giratina": "Slow",
	"cresselia": "Slow",
	"phione": "Slow",
	"manaphy": "Slow",
	"darkrai": "Slow",
	"shayminland": "Medium Slow",
	"arceus": "Slow",
	"victini": "Slow",
	"snivy": "Medium Slow",
	"servine": "Medium Slow",
	"serperior": "Medium Slow",
	"tepig": "Medium Slow",
	"pignite": "Medium Slow",
	"emboar": "Medium Slow",
	"oshawott": "Medium Slow",
	"dewott": "Medium Slow",
	"samurott": "Medium Slow",
	"patrat": "Medium Fast",
	"watchog": "Medium Fast",
	"lillipup": "Medium Slow",
	"herdier": "Medium Slow",
	"stoutland": "Medium Slow",
	"purrloin": "Medium Fast",
	"liepard": "Medium Fast",
	"pansage": "Medium Fast",
	"simisage": "Medium Fast",
	"pansear": "Medium Fast",
	"simisear": "Medium Fast",
	"panpour": "Medium Fast",
	"simipour": "Medium Fast",
	"munna": "Fast",
	"musharna": "Fast",
	"pidove": "Medium Slow",
	"tranquill": "Medium Slow",
	"unfezant": "Medium Slow",
	"blitzle": "Medium Fast",
	"zebstrika": "Medium Fast",
	"roggenrola": "Medium Slow",
	"boldore": "Medium Slow",
	"gigalith": "Medium Slow",
	"woobat": "Medium Fast",
	"swoobat": "Medium Fast",
	"drilbur": "Medium Fast",
	"excadrill": "Medium Fast",
	"audino": "Fast",
	"timburr": "Medium Slow",
	"gurdurr": "Medium Slow",
	"conkeldurr": "Medium Slow",
	"tympole": "Medium Slow",
	"palpitoad": "Medium Slow",
	"seismitoad": "Medium Slow",
	"throh": "Medium Fast",
	"sawk": "Medium Fast",
	"sewaddle": "Medium Slow",
	"swadloon": "Medium Slow",
	"leavanny": "Medium Slow",
	"venipede": "Medium Slow",
	"whirlipede": "Medium Slow",
	"scolipede": "Medium Slow",
	"cottonee": "Medium Fast",
	"whimsicott": "Medium Fast",
	"petilil": "Medium Fast",
	"lilligant": "Medium Fast",
	"basculinredstriped": "Medium Fast",
	"sandile": "Medium Slow",
	"krokorok": "Medium Slow",
	"krookodile": "Medium Slow",
	"darumaka": "Medium Slow",
	"darmanitan": "Medium Slow",
	"maractus": "Medium Fast",
	"dwebble": "Medium Fast",
	"crustle": "Medium Fast",
	"scraggy": "Medium Fast",
	"scrafty": "Medium Fast",
	"sigilyph": "Medium Fast",
	"yamask": "Medium Fast",
	"cofagrigus": "Medium Fast",
	"tirtouga": "Medium Fast",
	"carracosta": "Medium Fast",
	"archen": "Medium Fast",
	"archeops": "Medium Fast",
	"trubbish": "Medium Fast",
	"garbodor": "Medium Fast",
	"zorua": "Medium Slow",
	"zoroark": "Medium Slow",
	"minccino": "Fast",
	"cinccino": "Fast",
	"gothita": "Medium Slow",
	"gothorita": "Medium Slow",
	"gothitelle": "Medium Slow",
	"solosis": "Medium Slow",
	"duosion": "Medium Slow",
	"reuniclus": "Medium Slow",
	"ducklett": "Medium Fast",
	"swanna": "Medium Fast",
	"vanillite": "Slow",
	"vanillish": "Slow",
	"vanilluxe": "Slow",
	"deerling": "Medium Fast",
	"sawsbuck": "Medium Fast",
	"emolga": "Medium Fast",
	"karrablast": "Medium Fast",
	"escavalier": "Medium Fast",
	"foongus": "Medium Fast",
	"amoonguss": "Medium Fast",
	"frillish": "Medium Fast",
	"jellicent": "Medium Fast",
	"alomomola": "Fast",
	"joltik": "Medium Fast",
	"galvantula": "Medium Fast",
	"ferroseed": "Medium Fast",
	"ferrothorn": "Medium Fast",
	"klink": "Medium Slow",
	"klang": "Medium Slow",
	"klinklang": "Medium Slow",
	"tynamo": "Slow",
	"eelektrik": "Slow",
	"eelektross": "Slow",
	"elgyem": "Medium Fast",
	"beheeyem": "Medium Fast",
	"litwick": "Medium Slow",
	"lampent": "Medium Slow",
	"chandelure": "Medium Slow",
	"axew": "Slow",
	"fraxure": "Slow",
	"haxorus": "Slow",
	"cubchoo": "Medium Fast",
	"beartic": "Medium Fast",
	"cryogonal": "Medium Fast",
	"shelmet": "Medium Fast",
	"accelgor": "Medium Fast",
	"stunfisk": "Medium Fast",
	"mienfoo": "Medium Slow",
	"mienshao": "Medium Slow",
	"druddigon": "Medium Fast",
	"golett": "Medium Fast",
	"golurk": "Medium Fast",
	"pawniard": "Medium Fast",
	"bisharp": "Medium Fast",
	"bouffalant": "Medium Fast",
	"rufflet": "Slow",
	"braviary": "Slow",
	"vullaby": "Slow",
	"mandibuzz": "Slow",
	"heatmor": "Medium Fast",
	"durant": "Medium Fast",
	"deino": "Slow",
	"zweilous": "Slow",
	"hydreigon": "Slow",
	"larvesta": "Slow",
	"volcarona": "Slow",
	"cobalion": "Slow",
	"terrakion": "Slow",
	"virizion": "Slow",
	"tornadus": "Slow",
	"thundurus": "Slow",
	"reshiram": "Slow",
	"zekrom": "Slow",
	"landorus": "Slow",
	"kyurem": "Slow",
	"keldeo": "Slow",
	"meloetta": "Slow",
	"genesect": "Slow",
	"chespin": "Medium Slow",
	"quilladin": "Medium Slow",
	"chesnaught": "Medium Slow",
	"fennekin": "Medium Slow",
	"braixen": "Medium Slow",
	"delphox": "Medium Slow",
	"froakie": "Medium Slow",
	"frogadier": "Medium Slow",
	"greninja": "Medium Slow",
	"bunnelby": "Medium Fast",
	"diggersby": "Medium Fast",
	"fletchling": "Medium Slow",
	"fletchinder": "Medium Slow",
	"talonflame": "Medium Slow",
	"scatterbug": "Medium Fast",
	"spewpa": "Medium Fast",
	"vivillon": "Medium Fast",
	"litleo": "Medium Slow",
	"pyroar": "Medium Slow",
	"flabebe": "Medium Fast",
	"floette": "Medium Fast",
	"florges": "Medium Fast",
	"skiddo": "Medium Fast",
	"gogoat": "Medium Fast",
	"pancham": "Medium Fast",
	"pangoro": "Medium Fast",
	"furfrou": "Medium Fast",
	"espurr": "Medium Fast",
	"meowstic": "Medium Fast",
	"honedge": "Medium Fast",
	"doublade": "Medium Fast",
	"aegislash": "Medium Fast",
	"spritzee": "Medium Fast",
	"aromatisse": "Medium Fast",
	"swirlix": "Medium Fast",
	"slurpuff": "Medium Fast",
	"inkay": "Medium Fast",
	"malamar": "Medium Fast",
	"binacle": "Medium Fast",
	"barbaracle": "Medium Fast",
	"skrelp": "Medium Fast",
	"dragalge": "Medium Fast",
	"clauncher": "Slow",
	"clawitzer": "Slow",
	"helioptile": "Medium Fast",
	"heliolisk": "Medium Fast",
	"tyrunt": "Medium Fast",
	"tyrantrum": "Medium Fast",
	"amaura": "Medium Fast",
	"aurorus": "Medium Fast",
	"sylveon": "Medium Fast",
	"hawlucha": "Medium Fast",
	"dedenne": "Medium Fast",
	"carbink": "Slow",
	"goomy": "Slow",
	"sliggoo": "Slow",
	"goodra": "Slow",
	"klefki": "Fast",
	"phantump": "Medium Fast",
	"trevenant": "Medium Fast",
	"pumpkaboo": "Medium Fast",
	"gourgeist": "Medium Fast",
	"bergmite": "Medium Fast",
	"avalugg": "Medium Fast",
	"noibat": "Medium Fast",
	"noivern": "Medium Fast",
	"xerneas": "Slow",
	"yveltal": "Slow",
	"zygarde50": "Slow",
	"diancie": "Slow",
	"hoopa": "Slow",
	"volcanion": "Slow",
	"rowlet": "Medium Slow",
	"dartrix": "Medium Slow",
	"decidueye": "Medium Slow",
	"litten": "Medium Slow",
	"torracat": "Medium Slow",
	"incineroar": "Medium Slow",
	"popplio": "Medium Slow",
	"brionne": "Medium Slow",
	"primarina": "Medium Slow",
	"pikipek": "Medium Fast",
	"trumbeak": "Medium Fast",
	"toucannon": "Medium Fast",
	"yungoos": "Medium Fast",
	"gumshoos": "Medium Fast",
	"grubbin": "Medium Fast",
	"charjabug": "Medium Fast",
	"vikavolt": "Medium Fast",
	"crabrawler": "Medium Fast",
	"crabominable": "Medium Fast",
	"oricorio": "Medium Fast",
	"cutiefly": "Medium Fast",
	"ribombee": "Medium Fast",
	"rockruff": "Medium Fast",
	"lycanroc": "Medium Fast",
	"wishiwashi": "Fast",
	"mareanie": "Medium Fast",
	"toxapex": "Medium Fast",
	"mudbray": "Medium Fast",
	"mudsdale": "Medium Fast",
	"dewpider": "Medium Fast",
	"araquanid": "Medium Fast",
	"fomantis": "Medium Fast",
	"lurantis": "Medium Fast",
	"morelull": "Medium Fast",
	"shiinotic": "Medium Fast",
	"salandit": "Medium Fast",
	"salazzle": "Medium Fast",
	"stufful": "Medium Fast",
	"bewear": "Medium Fast",
	"bounsweet": "Medium Slow",
	"steenee": "Medium Slow",
	"tsareena": "Medium Slow",
	"comfey": "Fast",
	"oranguru": "Slow",
	"passimian": "Slow",
	"wimpod": "Medium Fast",
	"golisopod": "Medium Fast",
	"sandygast": "Medium Fast",
	"palossand": "Medium Fast",
	"pyukumuku": "Fast",
	"typenull": "Slow",
	"silvally": "Slow",
	"minior": "Medium Slow",
	"komala": "Slow",
	"turtonator": "Medium Fast",
	"togedemaru": "Medium Fast",
	"mimikyu": "Medium Fast",
	"bruxish": "Medium Fast",
	"drampa": "Medium Fast",
	"dhelmise": "Medium Fast",
	"jangmoo": "Slow",
	"hakamoo": "Slow",
	"kommoo": "Slow",
	"tapukoko": "Slow",
	"tapulele": "Slow",
	"tapubulu": "Slow",
	"tapufini": "Slow",
	"cosmog": "Slow",
	"cosmoem": "Slow",
	"solgaleo": "Slow",
	"lunala": "Slow",
	"nihilego": "Slow",
	"buzzwole": "Slow",
	"pheromosa": "Slow",
	"xurkitree": "Slow",
	"celesteela": "Slow",
	"kartana": "Slow",
	"guzzlord": "Slow",
	"necrozma": "Slow",
	"magearna": "Slow",
	"marshadow": "Slow",
	"poipole": "Slow",
	"naganadel": "Slow",
	"stakataka": "Slow",
	"blacephalon": "Slow",
	"zeraora": "Slow",
	"meltan": "Slow",
	"melmetal": "Slow",
	"grookey": "Medium Slow",
	"thwackey": "Medium Slow",
	"rillaboom": "Medium Slow",
	"scorbunny": "Medium Slow",
	"raboot": "Medium Slow",
	"cinderace": "Medium Slow",
	"sobble": "Medium Slow",
	"drizzile": "Medium Slow",
	"inteleon": "Medium Slow",
	"skwovet": "Medium Fast",
	"greedent": "Medium Fast",
	"rookidee": "Medium Slow",
	"corvisquire": "Medium Slow",
	"corviknight": "Medium Slow",
	"blipbug": "Medium Fast",
	"dottler": "Medium Fast",
	"orbeetle": "Medium Fast",
	"nickit": "Fast",
	"thievul": "Fast",
	"gossifleur": "Medium Fast",
	"eldegoss": "Medium Fast",
	"wooloo": "Medium Fast",
	"dubwool": "Medium Fast",
	"chewtle": "Medium Fast",
	"drednaw": "Medium Fast",
	"yamper": "Fast",
	"boltund": "Fast",
	"rolycoly": "Medium Slow",
	"carkol": "Medium Slow",
	"coalossal": "Medium Slow",
	"applin": "Erratic",
	"flapple": "Erratic",
	"appletun": "Erratic",
	"silicobra": "Medium Fast",
	"sandaconda": "Medium Fast",
	"cramorant": "Medium Fast",
	"arrokuda": "Slow",
	"barraskewda": "Slow",
	"toxel": "Medium Slow",
	"toxtricity": "Medium Slow",
	"sizzlipede": "Medium Fast",
	"centiskorch": "Medium Fast",
	"clobbopus": "Medium Slow",
	"grapploct": "Medium Slow",
	"sinistea": "Medium Fast",
	"polteageist": "Medium Fast",
	"hatenna": "Slow",
	"hattrem": "Slow",
	"hatterene": "Slow",
	"impidimp": "Medium Fast",
	"morgrem": "Medium Fast",
	"grimmsnarl": "Medium Fast",
	"obstagoon": "Medium Fast",
	"perrserker": "Medium Fast",
	"cursola": "Fast",
	"sirfetchd": "Medium Fast",
	"mrrime": "Medium Fast",
	"runerigus": "Medium Fast",
	"milcery": "Medium Fast",
	"alcremie": "Medium Fast",
	"falinks": "Medium Fast",
	"pincurchin": "Medium Fast",
	"snom": "Medium Fast",
	"frosmoth": "Medium Fast",
	"stonjourner": "Slow",
	"eiscue": "Slow",
	"indeedee": "Fast",
	"morpeko": "Medium Fast",
	"cufant": "Medium Fast",
	"copperajah": "Medium Fast",
	"dracozolt": "Slow",
	"arctozolt": "Slow",
	"dracovish": "Slow",
	"arctovish": "Slow",
	"duraludon": "Medium Fast",
	"dreepy": "Slow",
	"drakloak": "Slow",
	"dragapult": "Slow",
	"zacian": "Slow",
	"zamazenta": "Slow",
	"eternatus": "Slow",
	"kubfu": "Slow",
	"urshifu": "Slow",
	"zarude": "Slow",
	"regieleki": "Slow",
	"regidrago": "Slow",
	"glastrier": "Slow",
	"spectrier": "Slow",
	"calyrex": "Slow",
	"wyrdeer": "Slow",
	"kleavor": "Medium Fast",
	"ursaluna": "Medium Fast",
	"basculegion": "Medium Fast",
	"sneasler": "Medium Slow",
	"overqwil": "Medium Fast",
	"enamorus": "Slow",
	"sprigatito": "Medium Slow",
	"floragato": "Medium Slow",
	"meowscarada": "Medium Slow",
	"fuecoco": "Medium Slow",
	"crocalor": "Medium Slow",
	"skeledirge": "Medium Slow",
	"quaxly": "Medium Slow",
	"quaxwell": "Medium Slow",
	"quaquaval": "Medium Slow",
	"lechonk": "Medium Fast",
	"oinkologne": "Medium Fast",
	"tarountula": "Erratic",
	"spidops": "Erratic",
	"nymble": "Medium Fast",
	"lokix": "Medium Fast",
	"pawmi": "Medium Fast",
	"pawmo": "Medium Fast",
	"pawmot": "Medium Fast",
	"tandemaus": "Fast",
	"mausholdfamilyoffour": "Fast",
	"fidough": "Medium Slow",
	"dachsbun": "Medium Slow",
	"smoliv": "Medium Slow",
	"dolliv": "Medium Slow",
	"arboliva": "Medium Slow",
	"squawkabillygreenplumage": "Erratic",
	"nacli": "Medium Slow",
	"naclstack": "Medium Slow",
	"garganacl": "Medium Slow",
	"charcadet": "Slow",
	"armarouge": "Slow",
	"ceruledge": "Slow",
	"tadbulb": "Medium Fast",
	"bellibolt": "Medium Fast",
	"wattrel": "Medium Slow",
	"kilowattrel": "Medium Slow",
	"maschiff": "Medium Slow",
	"mabosstiff": "Medium Slow",
	"shroodle": "Medium Slow",
	"grafaiai": "Medium Slow",
	"bramblin": "Medium Fast",
	"brambleghast": "Medium Fast",
	"toedscool": "Medium Slow",
	"toedscruel": "Medium Slow",
	"klawf": "Medium Fast",
	"capsakid": "Medium Fast",
	"scovillain": "Medium Fast",
	"rellor": "Fast",
	"rabsca": "Fast",
	"flittle": "Medium Slow",
	"espathra": "Medium Slow",
	"tinkatink": "Medium Slow",
	"tinkatuff": "Medium Slow",
	"tinkaton": "Medium Slow",
	"wiglett": "Medium Fast",
	"wugtrio": "Medium Fast",
	"bombirdier": "Slow",
	"finizen": "Slow",
	"palafinzero": "Slow",
	"varoom": "Medium Fast",
	"revavroom": "Medium Fast",
	"cyclizar": "Medium Slow",
	"orthworm": "Slow",
	"glimmet": "Medium Slow",
	"glimmora": "Medium Slow",
	"greavard": "Medium Slow",
	"houndstone": "Medium Slow",
	"flamigo": "Medium Slow",
	"cetoddle": "Medium Slow",
	"cetitan": "Medium Slow",
	"veluza": "Fast",
	"dondozo": "Slow",
	"tatsugiricurly": "Medium Slow",
	"annihilape": "Medium Fast",
	"clodsire": "Medium Fast",
	"farigiraf": "Medium Fast",
	"dudunsparcetwosegment": "Medium Fast",
	"kingambit": "Medium Fast",
	"greattusk": "Slow",
	"screamtail": "Slow",
	"brutebonnet": "Slow",
	"fluttermane": "Slow",
	"slitherwing": "Slow",
	"sandyshocks": "Slow",
	"irontreads": "Slow",
	"ironbundle": "Slow",
	"ironhands": "Slow",
	"ironjugulis": "Slow",
	"ironmoth": "Slow",
	"ironthorns": "Slow",
	"frigibax": "Slow",
	"arctibax": "Slow",
	"baxcalibur": "Slow",
	"gimmighoul": "Slow",
	"gholdengo": "Slow",
	"wochien": "Slow",
	"chienpao": "Slow",
	"tinglu": "Slow",
	"chiyu": "Slow",
	"roaringmoon": "Slow",
	"ironvaliant": "Slow",
	"koraidon": "Slow",
	"miraidon": "Slow",
	"walkingwake": "Slow",
	"ironleaves": "Slow",
	"dipplin": "Slow",
	"poltchageist": "Slow",
	"sinistcha": "Slow",
	"okidogi": "Slow",
	"munkidori": "Slow",
	"fezandipiti": "Slow",
	"ogerpon": "Slow",
	"archaludon": "Medium Fast",
	"hydrapple": "Erratic",
	"gougingfire": "Slow",
	"ragingbolt": "Slow",
	"ironboulder": "Slow",
	"ironcrown": "Slow",
	"terapagos": "Slow",
	"pecharunt": "Slow",
	"deoxysattack": "Slow",
	"deoxysdefense": "Slow",
	"deoxysspeed": "Slow",
	"wormadamsandy": "Medium Fast",
	"wormadamtrash": "Medium Fast",
	"shayminsky": "Medium Slow",
	"giratinaorigin": "Slow",
	"rotomheat": "Medium Fast",
	"rotomwash": "Medium Fast",
	"rotomfrost": "Medium Fast",
	"rotomfan": "Medium Fast",
	"rotommow": "Medium Fast",
	"castformsunny": "Medium Fast",
	"castformrainy": "Medium Fast",
	"castformsnowy": "Medium Fast",
	"basculinbluestriped": "Medium Fast",
	"darmanitanzen": "Medium Slow",
	"meloettapirouette": "Slow",
	"tornadustherian": "Slow",
	"thundurustherian": "Slow",
	"landorustherian": "Slow",
	"kyuremblack": "Slow",
	"kyuremwhite": "Slow",
	"keldeoresolute": "Slow",
	"meowsticfe": "Medium Fast",
	"aegislashblade": "Medium Fast",
	"pumpkaboosmall": "Medium Fast",
	"pumpkaboolarge": "Medium Fast",
	"pumpkaboosuper": "Medium Fast",
	"gourgeistsmall": "Medium Fast",
	"gourgeistlarge": "Medium Fast",
	"gourgeistsuper": "Medium Fast",
	"venusaurmega": "Medium Slow",
	"charizardmegax": "Medium Slow",
	"charizardmegay": "Medium Slow",
	"blastoisemega": "Medium Slow",
	"alakazammega": "Medium Slow",
	"gengarmega": "Medium Slow",
	"kangaskhanmega": "Medium Fast",
	"pinsirmega": "Slow",
	"gyaradosmega": "Slow",
	"aerodactylmega": "Slow",
	"mewtwomegax": "Slow",
	"mewtwomegay": "Slow",
	"ampharosmega": "Medium Slow",
	"scizormega": "Medium Fast",
	"heracrossmega": "Slow",
	"houndoommega": "Slow",
	"tyranitarmega": "Slow",
	"blazikenmega": "Medium Slow",
	"gardevoirmega": "Slow",
	"mawilemega": "Fast",
	"aggronmega": "Slow",
	"medichammega": "Medium Fast",
	"manectricmega": "Slow",
	"banettemega": "Fast",
	"absolmega": "Medium Slow",
	"garchompmega": "Slow",
	"lucariomega": "Medium Slow",
	"abomasnowmega": "Slow",
	"floetteeternal": "Medium Fast",
	"latiasmega": "Slow",
	"latiosmega": "Slow",
	"swampertmega": "Medium Slow",
	"sceptilemega": "Medium Slow",
	"sableyemega": "Medium Slow",
	"altariamega": "Erratic",
	"gallademega": "Slow",
	"audinomega": "Fast",
	"sharpedomega": "Slow",
	"slowbromega": "Medium Fast",
	"steelixmega": "Medium Fast",
	"pidgeotmega": "Medium Slow",
	"glaliemega": "Medium Fast",
	"dianciemega": "Slow",
	"metagrossmega": "Slow",
	"kyogreprimal": "Slow",
	"groudonprimal": "Slow",
	"rayquazamega": "Slow",
	"pikachurockstar": "Medium Fast",
	"pikachubelle": "Medium Fast",
	"pikachupopstar": "Medium Fast",
	"pikachuphd": "Medium Fast",
	"pikachulibre": "Medium Fast",
	"pikachucosplay": "Medium Fast",
	"hoopaunbound": "Slow",
	"cameruptmega": "Medium Fast",
	"lopunnymega": "Medium Fast",
	"salamencemega": "Slow",
	"beedrillmega": "Medium Fast",
	"rattataalola": "Medium Fast",
	"raticatealola": "Medium Fast",
	"raticatetotemalola": "Medium Fast",
	"pikachuoriginalcap": "Medium Fast",
	"pikachuhoenncap": "Medium Fast",
	"pikachusinnohcap": "Medium Fast",
	"pikachuunovacap": "Medium Fast",
	"pikachukaloscap": "Medium Fast",
	"pikachualolacap": "Medium Fast",
	"raichualola": "Medium Fast",
	"sandshrewalola": "Medium Fast",
	"sandslashalola": "Medium Fast",
	"vulpixalola": "Medium Fast",
	"ninetalesalola": "Medium Fast",
	"diglettalola": "Medium Fast",
	"dugtrioalola": "Medium Fast",
	"meowthalola": "Medium Fast",
	"persianalola": "Medium Fast",
	"geodudealola": "Medium Slow",
	"graveleralola": "Medium Slow",
	"golemalola": "Medium Slow",
	"grimeralola": "Medium Fast",
	"mukalola": "Medium Fast",
	"exeggutoralola": "Slow",
	"marowakalola": "Medium Fast",
	"greninjabattlebond": "Medium Slow",
	"greninjaash": "Medium Slow",
	"zygarde10powerconstruct": "Slow",
	"zygarde50powerconstruct": "Slow",
	"zygardecomplete": "Slow",
	"gumshoostotem": "Medium Fast",
	"vikavolttotem": "Medium Fast",
	"oricoriopompom": "Medium Fast",
	"oricoriopau": "Medium Fast",
	"oricoriosensu": "Medium Fast",
	"lycanrocmidnight": "Medium Fast",
	"wishiwashischool": "Fast",
	"lurantistotem": "Medium Fast",
	"salazzletotem": "Medium Fast",
	"miniororangemeteor": "Medium Slow",
	"minioryellowmeteor": "Medium Slow",
	"miniorgreenmeteor": "Medium Slow",
	"miniorbluemeteor": "Medium Slow",
	"miniorindigometeor": "Medium Slow",
	"miniorvioletmeteor": "Medium Slow",
	"miniorred": "Medium Slow",
	"miniororange": "Medium Slow",
	"minioryellow": "Medium Slow",
	"miniorgreen": "Medium Slow",
	"miniorblue": "Medium Slow",
	"miniorindigo": "Medium Slow",
	"miniorviolet": "Medium Slow",
	"mimikyubusted": "Medium Fast",
	"mimikyutotem": "Medium Fast",
	"mimikyutotembusted": "Medium Fast",
	"kommoototem": "Slow",
	"magearnaoriginal": "Slow",
	"pikachupartnercap": "Medium Fast",
	"marowaktotem": "Medium Fast",
	"ribombeetotem": "Medium Fast",
	"rockruffowntempo": "Medium Fast",
	"lycanrocdusk": "Medium Fast",
	"araquanidtotem": "Medium Fast",
	"togedemarutotem": "Medium Fast",
	"necrozmadusk": "Slow",
	"necrozmadawn": "Slow",
	"necrozmaultra": "Slow",
	"pikachustarter": "Medium Fast",
	"eeveestarter": "Medium Fast",
	"pikachuworldcap": "Medium Fast",
	"meowthgalar": "Medium Fast",
	"ponytagalar": "Medium Fast",
	"rapidashgalar": "Medium Fast",
	"slowpokegalar": "Medium Fast",
	"slowbrogalar": "Medium Fast",
	"farfetchdgalar": "Medium Fast",
	"weezinggalar": "Medium Fast",
	"mrmimegalar": "Medium Fast",
	"articunogalar": "Slow",
	"zapdosgalar": "Slow",
	"moltresgalar": "Slow",
	"slowkinggalar": "Medium Fast",
	"corsolagalar": "Fast",
	"zigzagoongalar": "Medium Fast",
	"linoonegalar": "Medium Fast",
	"darumakagalar": "Medium Slow",
	"darmanitangalar": "Medium Slow",
	"darmanitangalarzen": "Medium Slow",
	"yamaskgalar": "Medium Fast",
	"stunfiskgalar": "Medium Fast",
	"zygarde10": "Slow",
	"cramorantgulping": "Medium Fast",
	"cramorantgorging": "Medium Fast",
	"toxtricitylowkey": "Medium Slow",
	"eiscueno": "Slow",
	"indeedeefe": "Fast",
	"morpekohangry": "Medium Fast",
	"zaciancrowned": "Slow",
	"zamazentacrowned": "Slow",
	"eternatuseternamax": "Slow",
	"urshifurapidstrike": "Slow",
	"zarudedada": "Slow",
	"calyrexshadow": "Slow",
	"venusaurgmax": "Medium Slow",
	"charizardgmax": "Medium Slow",
	"blastoisegmax": "Medium Slow",
	"butterfreegmax": "Medium Fast",
	"pikachugmax": "Medium Fast",
	"meowthgmax": "Medium Fast",
	"machampgmax": "Medium Slow",
	"gengargmax": "Medium Slow",
	"kinglergmax": "Medium Fast",
	"laprasgmax": "Slow",
	"eeveegmax": "Medium Fast",
	"snorlaxgmax": "Slow",
	"garbodorgmax": "Medium Fast",
	"melmetalgmax": "Slow",
	"rillaboomgmax": "Medium Slow",
	"cinderacegmax": "Medium Slow",
	"inteleongmax": "Medium Slow",
	"corviknightgmax": "Medium Slow",
	"orbeetlegmax": "Medium Fast",
	"drednawgmax": "Medium Fast",
	"coalossalgmax": "Medium Slow",
	"flapplegmax": "Erratic",
	"appletungmax": "Erratic",
	"sandacondagmax": "Medium Fast",
	"toxtricityampedgmax": "Medium Slow",
	"centiskorchgmax": "Medium Fast",
	"hatterenegmax": "Slow",
	"grimmsnarlgmax": "Medium Fast",
	"alcremiegmax": "Medium Fast",
	"copperajahgmax": "Medium Fast",
	"duraludongmax": "Medium Fast",
	"urshifusinglestrikegmax": "Slow",
	"urshifurapidstrikegmax": "Slow",
	"toxtricitylowkeygmax": "Medium Slow",
	"growlithehisui": "Slow",
	"arcaninehisui": "Slow",
	"voltorbhisui": "Medium Fast",
	"electrodehisui": "Medium Fast",
	"typhlosionhisui": "Medium Slow",
	"qwilfishhisui": "Medium Fast",
	"sneaselhisui": "Medium Slow",
	"samurotthisui": "Medium Slow",
	"lilliganthisui": "Medium Fast",
	"zoruahisui": "Medium Slow",
	"zoroarkhisui": "Medium Slow",
	"braviaryhisui": "Slow",
	"sliggoohisui": "Slow",
	"goodrahisui": "Slow",
	"avalugghisui": "Medium Fast",
	"decidueyehisui": "Medium Slow",
	"dialgaorigin": "Slow",
	"palkiaorigin": "Slow",
	"basculinwhitestriped": "Medium Fast",
	"basculegionfe": "Medium Fast",
	"enamorustherian": "Slow",
	"taurospaldeacombatbreed": "Slow",
	"taurospaldeablazebreed": "Slow",
	"taurospaldeaaquabreed": "Slow",
	"wooperpaldea": "Medium Fast",
	"oinkolognefe": "Medium Fast",
	"dudunsparcethreesegment": "Medium Fast",
	"palafinhero": "Slow",
	"mausholdfamilyofthree": "Fast",
	"tatsugiridroopy": "Medium Slow",
	"tatsugiristretchy": "Medium Slow",
	"squawkabillyblueplumage": "Erratic",
	"squawkabillyyellowplumage": "Erratic",
	"squawkabillywhiteplumage": "Erratic",
	"gimmighoulroaming": "Slow",
	"koraidonlimitedbuild": "Slow",
	"koraidonsprintingbuild": "Slow",
	"koraidonswimmingbuild": "Slow",
	"koraidonglidingbuild": "Slow",
	"miraidonlowpowermode": "Slow",
	"miraidondrivemode": "Slow",
	"miraidonaquaticmode": "Slow",
	"miraidonglidemode": "Slow",
	"ursalunabloodmoon": "Medium Fast",
	"ogerponwellspringmask": "Slow",
	"ogerponhearthflamemask": "Slow",
	"ogerponcornerstonemask": "Slow",
	"terapagosterastal": "Slow",
	"terapagosstellar": "Slow",
};
