export type EggTier = 'Common' | 'Rare' | 'Epic' | 'Legendary';

export const EGG_POOLS: Record<EggTier, string[]> = {
	Common: [
		'caterpie', 'weedle', 'pidgey', 'rattata', 'spearow', 'ekans', 'sandshrew',
		'nidoranf', 'nidoranm', 'vulpix', 'zubat', 'oddish', 'paras', 'venonat',
		'diglett', 'meowth', 'psyduck', 'mankey', 'growlithe', 'poliwag', 'abra',
		'machop', 'bellsprout', 'tentacool', 'geodude', 'ponyta', 'slowpoke',
		'magnemite', 'farfetchd', 'doduo', 'seel', 'grimer', 'shellder', 'gastly',
		'onix', 'drowzee', 'krabby', 'voltorb', 'exeggcute', 'cubone', 'koffing',
		'rhyhorn', 'tangela', 'horsea', 'goldeen', 'staryu', 'magikarp', 'ditto',

		'sentret', 'hoothoot', 'ledyba', 'spinarak', 'chinchou', 'pichu', 'cleffa',
		'igglybuff', 'togepi', 'mareep', 'hoppip', 'aipom', 'sunkern', 'yanma',
		'wooper', 'murkrow', 'misdreavus', 'unown', 'girafarig', 'pineco', 'dunsparce',
		'gligar', 'snubbull', 'qwilfish', 'shuckle', 'sneasel', 'teddiursa', 'slugma',
		'swinub', 'corsola', 'remoraid', 'delibird', 'houndour', 'phanpy', 'stantler',
		'smeargle', 'tyrogue', 'smoochum', 'elekid', 'magby',

		'poochyena', 'zigzagoon', 'wurmple', 'lotad', 'seedot', 'taillow', 'wingull',
		'ralts', 'surskit', 'shroomish', 'slakoth', 'nincada', 'whismur', 'makuhita',
		'azurill', 'nosepass', 'skitty', 'sableye', 'mawile', 'aron', 'meditite',
		'electrike', 'plusle', 'minun', 'volbeat', 'illumise', 'gulpin', 'carvanha',
		'wailmer', 'numel', 'spoink', 'spinda', 'trapinch', 'cacnea', 'swablu',
		'zangoose', 'seviper', 'lunatone', 'solrock', 'barboach', 'corphish', 'baltoy',
		'lileep', 'anorith', 'feebas', 'castform', 'kecleon', 'shuppet', 'duskull',
		'wynaut', 'snorunt', 'spheal', 'clamperl', 'luvdisc',

		'starly', 'bidoof', 'kricketot', 'shinx', 'cranidos', 'shieldon', 'burmy',
		'combee', 'pachirisu', 'buizel', 'cherubi', 'shellos', 'drifloon', 'buneary',
		'glameow', 'chingling', 'stunky', 'bronzor', 'bonsly', 'mimejr', 'happiny',
		'chatot', 'hippopotas', 'skorupi', 'croagunk', 'carnivine', 'finneon',
		'mantyke', 'snover',

		'patrat', 'lillipup', 'purrloin', 'pansage', 'pansear', 'panpour', 'munna',
		'pidove', 'blitzle', 'roggenrola', 'woobat', 'drilbur', 'audino', 'timburr',
		'tympole', 'throh', 'sawk', 'sewaddle', 'venipede', 'cottonee', 'petilil',
		'basculin', 'sandile', 'darumaka', 'maractus', 'dwebble', 'scraggy', 'yamask',
		'tirtouga', 'archen', 'trubbish', 'minccino', 'gothita', 'solosis', 'ducklett',
		'vanillite', 'deerling', 'emolga', 'karrablast', 'foongus', 'frillish',
		'alomomola', 'joltik', 'ferroseed', 'klink', 'tynamo', 'elgyem', 'litwick',
		'axew', 'cubchoo', 'shelmet', 'stunfisk', 'mienfoo', 'golett', 'pawniard',
		'rufflet', 'vullaby', 'heatmor',

		'bunnelby', 'fletchling', 'scatterbug', 'litleo', 'flabebe', 'skiddo', 'pancham',
		'espurr', 'honedge', 'spritzee', 'swirlix', 'inkay', 'binacle', 'skrelp',
		'clauncher', 'helioptile', 'dedenne', 'phantump', 'pumpkaboo', 'bergmite', 'noibat',

		'pikipek', 'yungoos', 'grubbin', 'crabrawler', 'oricorio', 'cutiefly', 'rockruff',
		'wishiwashi', 'mareanie', 'mudbray', 'dewpider', 'fomantis', 'morelull', 'salandit',
		'stufful', 'bounsweet', 'wimpod', 'sandygast', 'pyukumuku', 'minior', 'komala',

		'skwovet', 'rookidee', 'blipbug', 'nickit', 'gossifleur', 'wooloo', 'chewtle',
		'yamper', 'rolycoly', 'applin', 'silicobra', 'arrokuda', 'toxel', 'sizzlipede',
		'clobbopus', 'sinistea', 'hatenna', 'impidimp', 'milcery', 'pincurchin', 'snom',
		'indeedee', 'cufant',

		'lechonk', 'tarountula', 'nymble', 'pawmi', 'tandemaus', 'fidough', 'smoliv',
		'squawkabilly', 'nacli', 'charcadet', 'tadbulb', 'wattrel', 'maschiff', 'shroodle',
		'bramblin', 'toedscool', 'klawf', 'capsakid', 'rellor', 'flittle', 'tinkatink',
		'wiglett', 'bombirdier', 'finizen', 'varoom', 'glimmet', 'greavard', 'cetoddle',
		'poltchageist',

		'rattataalola', 'sandshrewalola', 'vulpixalola', 'diglettalola', 'meowthalola',
		'geodudealola', 'grimeralola', 'ponytagalar', 'farfetchdgalar', 'corsolagalar',
		'zigzagoongalar', 'darumakagalar', 'yamaskgalar', 'stunfiskgalar', 'meowthgalar',
		'slowpokegalar', 'growlithehisui', 'voltorbhisui', 'qwilfishhisui', 'sneaselhisui',
		'basculinwhitestriped', 'wooperpaldea',
	],
	Rare: [
		'bulbasaur', 'charmander', 'squirtle', 'chikorita', 'cyndaquil', 'totodile',
		'treecko', 'torchic', 'mudkip', 'turtwig', 'chimchar', 'piplup', 'snivy', 'tepig',
		'oshawott', 'chespin', 'fennekin', 'froakie', 'rowlet', 'litten', 'popplio',
		'grookey', 'scorbunny', 'sobble', 'sprigatito', 'fuecoco', 'quaxly',

		'dratini', 'larvitar', 'bagon', 'beldum', 'gible', 'deino', 'goomy', 'jangmoo',
		'dreepy', 'frigibax',

		'eevee', 'aerodactyl', 'lapras', 'snorlax', 'scyther', 'pinsir', 'tauros',
		'kangaskhan', 'omanyte', 'kabuto', 'porygon', 'heracross', 'miltank', 'skarmory',
		'tropius', 'absol', 'relicanth', 'torkoal', 'munchlax', 'riolu', 'rotom',
		'spiritomb', 'zorua', 'zoruahisui', 'larvesta', 'sigilyph', 'druddigon',
		'bouffalant', 'durant', 'cryogonal', 'furfrou', 'hawlucha', 'carbink', 'klefki',
		'comfey', 'oranguru', 'passimian', 'togedemaru', 'bruxish', 'drampa', 'dhelmise',
		'turtonator', 'mimikyu', 'cramorant', 'falinks', 'stonjourner', 'eiscue', 'morpeko',
		'cyclizar', 'orthworm', 'flamigo', 'veluza', 'dondozo', 'tatsugiri', 'gimmighoul',
		'taurospaldeacombat', 'taurospaldeablaze', 'taurospaldeaaqua',
	],
	Epic: [
		'articuno', 'zapdos', 'moltres', 'articunogalar', 'zapdosgalar', 'moltresgalar',
		'raikou', 'entei', 'suicune',
		'regirock', 'regice', 'registeel', 'regieleki', 'regidrago',
		'latias', 'latios',
		'uxie', 'mesprit', 'azelf', 'heatran', 'cresselia',
		'cobalion', 'terrakion', 'virizion', 'tornadus', 'thundurus', 'landorus', 'enamorus',

		'tapukoko', 'tapulele', 'tapubulu', 'tapufini',
		'nihilego', 'buzzwole', 'pheromosa', 'xurkitree', 'celesteela', 'kartana',
		'guzzlord', 'poipole', 'stakataka', 'blacephalon',

		'typenull', 'phione', 'glastrier', 'spectrier', 'meltan', 'ogerpon', 'duraludon',

		'okidogi', 'munkidori', 'fezandipiti',
		'wochien', 'chienpao', 'tinglu', 'chiyu',

		'greattusk', 'screamtail', 'brutebonnet', 'fluttermane', 'slitherwing', 'sandyshocks',
		'irontreads', 'ironbundle', 'ironhands', 'ironjugulis', 'ironmoth', 'ironthorns',
		'roaringmoon', 'ironvaliant', 'walkingwake', 'ironleaves', 'gougingfire',
		'ragingbolt', 'ironboulder', 'ironcrown',
	],
	Legendary: [
		'mewtwo', 'mew', 'lugia', 'hooh', 'celebi',
		'kyogre', 'groudon', 'rayquaza', 'jirachi', 'deoxys',
		'dialga', 'palkia', 'giratina', 'manaphy', 'darkrai', 'shaymin', 'arceus',
		'reshiram', 'zekrom', 'kyurem', 'keldeo', 'meloetta', 'genesect', 'victini',
		'xerneas', 'yveltal', 'zygarde', 'diancie', 'hoopa', 'volcanion',
		'cosmog', 'necrozma', 'magearna', 'marshadow', 'zeraora',
		'zacian', 'zamazenta', 'eternatus', 'kubfu', 'zarude', 'calyrex',
		'koraidon', 'miraidon', 'terapagos', 'pecharunt',
	],
};
export const STARTER_COSTS: Record<string, number> = {
	caterpie: 1, weedle: 1, pidgey: 1, rattata: 1, spearow: 1, ekans: 1, sandshrew: 1,
	sentret: 1, hoothoot: 1, ledyba: 1, spinarak: 1, pichu: 1, cleffa: 1, igglybuff: 1,
	wurmple: 1, zigzagoon: 1, wingull: 1, taillow: 1, bidoof: 1, kricketot: 1,
	patrat: 1, purrloin: 1, pidove: 1, bunnelby: 1, fletchling: 1, scatterbug: 1,
	pikipek: 1, yungoos: 1, grubbin: 1, skwovet: 1, rookidee: 1, blipbug: 1,
	nickit: 1, lechonk: 1, tarountula: 1, nymble: 1,

	vulpix: 2, zubat: 2, oddish: 2, paras: 2, venonat: 2, diglett: 2, meowth: 2,
	psyduck: 2, mankey: 2, growlithe: 2, poliwag: 2, abra: 2, machop: 2,
	bellsprout: 2, tentacool: 2, geodude: 2, ponyta: 2, slowpoke: 2, magnemite: 2,
	doduo: 2, seel: 2, grimer: 2, shellder: 2, gastly: 2, onix: 2, drowzee: 2,
	krabby: 2, voltorb: 2, exeggcute: 2, cubone: 2, koffing: 2, rhyhorn: 2,
	tangela: 2, horsea: 2, goldeen: 2, staryu: 2, magikarp: 2, ditto: 2,
	nidoranf: 2, nidoranm: 2, farfetchd: 2,
	chinchou: 2, togepi: 2, mareep: 2, hoppip: 2, aipom: 2, sunkern: 2, yanma: 2,
	wooper: 2, murkrow: 2, misdreavus: 2, unown: 2, girafarig: 2, pineco: 2,
	dunsparce: 2, gligar: 2, snubbull: 2, qwilfish: 2, shuckle: 2, sneasel: 2,
	teddiursa: 2, slugma: 2, swinub: 2, corsola: 2, remoraid: 2, delibird: 2,
	houndour: 2, phanpy: 2, stantler: 2, smeargle: 2, tyrogue: 2, smoochum: 2,
	elekid: 2, magby: 2,
	poochyena: 2, lotad: 2, seedot: 2, ralts: 2, surskit: 2, shroomish: 2,
	slakoth: 2, nincada: 2, whismur: 2, makuhita: 2, azurill: 2, nosepass: 2,
	skitty: 2, sableye: 2, mawile: 2, aron: 2, meditite: 2, electrike: 2,
	plusle: 2, minun: 2, volbeat: 2, illumise: 2, gulpin: 2, carvanha: 2,
	wailmer: 2, numel: 2, spoink: 2, spinda: 2, trapinch: 2, cacnea: 2,
	swablu: 2, zangoose: 2, seviper: 2, lunatone: 2, solrock: 2, barboach: 2,
	corphish: 2, baltoy: 2, lileep: 2, anorith: 2, feebas: 2, castform: 2,
	kecleon: 2, shuppet: 2, duskull: 2, wynaut: 2, snorunt: 2, spheal: 2,
	clamperl: 2, luvdisc: 2,
	starly: 2, shinx: 2, cranidos: 2, shieldon: 2, burmy: 2, combee: 2,
	pachirisu: 2, buizel: 2, cherubi: 2, shellos: 2, drifloon: 2, buneary: 2,
	glameow: 2, chingling: 2, stunky: 2, bronzor: 2, bonsly: 2, mimejr: 2,
	happiny: 2, chatot: 2, hippopotas: 2, skorupi: 2, croagunk: 2, carnivine: 2,
	finneon: 2, mantyke: 2, snover: 2,
	lillipup: 2, pansage: 2, pansear: 2, panpour: 2, munna: 2, blitzle: 2,
	roggenrola: 2, woobat: 2, drilbur: 2, audino: 2, timburr: 2, tympole: 2,
	throh: 2, sawk: 2, sewaddle: 2, venipede: 2, cottonee: 2, petilil: 2,
	basculin: 2, sandile: 2, darumaka: 2, maractus: 2, dwebble: 2, scraggy: 2,
	yamask: 2, tirtouga: 2, archen: 2, trubbish: 2, minccino: 2, gothita: 2,
	solosis: 2, ducklett: 2, vanillite: 2, deerling: 2, emolga: 2, karrablast: 2,
	foongus: 2, frillish: 2, alomomola: 2, joltik: 2, ferroseed: 2, klink: 2,
	tynamo: 2, elgyem: 2, litwick: 2, axew: 2, cubchoo: 2, shelmet: 2,
	stunfisk: 2, mienfoo: 2, golett: 2, pawniard: 2, rufflet: 2, vullaby: 2,
	heatmor: 2,
	litleo: 2, flabebe: 2, skiddo: 2, pancham: 2, espurr: 2, honedge: 2,
	spritzee: 2, swirlix: 2, inkay: 2, binacle: 2, skrelp: 2, clauncher: 2,
	helioptile: 2, dedenne: 2, phantump: 2, pumpkaboo: 2, bergmite: 2, noibat: 2,
	crabrawler: 2, oricorio: 2, cutiefly: 2, rockruff: 2, wishiwashi: 2,
	mareanie: 2, mudbray: 2, dewpider: 2, fomantis: 2, morelull: 2, salandit: 2,
	stufful: 2, bounsweet: 2, wimpod: 2, sandygast: 2, pyukumuku: 2, minior: 2,
	komala: 2,
	gossifleur: 2, wooloo: 2, chewtle: 2, yamper: 2, rolycoly: 2, applin: 2,
	silicobra: 2, arrokuda: 2, toxel: 2, sizzlipede: 2, clobbopus: 2, sinistea: 2,
	hatenna: 2, impidimp: 2, milcery: 2, pincurchin: 2, snom: 2, indeedee: 2,
	cufant: 2,
	pawmi: 2, tandemaus: 2, fidough: 2, smoliv: 2, squawkabilly: 2, nacli: 2,
	charcadet: 2, tadbulb: 2, wattrel: 2, maschiff: 2, shroodle: 2, bramblin: 2,
	toedscool: 2, klawf: 2, capsakid: 2, rellor: 2, flittle: 2, tinkatink: 2,
	wiglett: 2, bombirdier: 2, finizen: 2, varoom: 2, glimmet: 2, greavard: 2,
	cetoddle: 2, poltchageist: 2,

	rattataalola: 2, sandshrewalola: 2, vulpixalola: 2, diglettalola: 2, meowthalola: 2,
	geodudealola: 2, grimeralola: 2, ponytagalar: 2, farfetchdgalar: 2, corsolagalar: 2,
	zigzagoongalar: 2, darumakagalar: 2, yamaskgalar: 2, stunfiskgalar: 2, meowthgalar: 2,
	slowpokegalar: 2, growlithehisui: 2, voltorbhisui: 2, qwilfishhisui: 2, sneaselhisui: 2,
	basculinwhitestriped: 2, wooperpaldea: 2,

	bulbasaur: 3, charmander: 3, squirtle: 3, chikorita: 3, cyndaquil: 3, totodile: 3,
	treecko: 3, torchic: 3, mudkip: 3, turtwig: 3, chimchar: 3, piplup: 3,
	snivy: 3, tepig: 3, oshawott: 3, chespin: 3, fennekin: 3, froakie: 3,
	rowlet: 3, litten: 3, popplio: 3, grookey: 3, scorbunny: 3, sobble: 3,
	sprigatito: 3, fuecoco: 3, quaxly: 3, eevee: 3,
	omanyte: 3, kabuto: 3, porygon: 3, tropius: 3, absol: 3, relicanth: 3,
	torkoal: 3, munchlax: 3, riolu: 3, zorua: 3, zoruahisui: 3, sigilyph: 3,
	druddigon: 3, bouffalant: 3, durant: 3, cryogonal: 3, furfrou: 3, hawlucha: 3,
	carbink: 3, klefki: 3, comfey: 3, oranguru: 3, passimian: 3, togedemaru: 3,
	bruxish: 3, drampa: 3, dhelmise: 3, turtonator: 3, cramorant: 3, falinks: 3,
	stonjourner: 3, eiscue: 3, morpeko: 3, cyclizar: 3, orthworm: 3, flamigo: 3,
	veluza: 3, tatsugiri: 3, gimmighoul: 3,

	scyther: 4, pinsir: 4, tauros: 4, lapras: 4, snorlax: 4, heracross: 4,
	skarmory: 4, spiritomb: 4, rotom: 4, mimikyu: 4,
	aerodactyl: 4, kangaskhan: 4, miltank: 4, larvesta: 4, dondozo: 4,
	taurospaldeacombat: 4, taurospaldeablaze: 4, taurospaldeaaqua: 4,
	meltan: 4, duraludon: 4,

	dratini: 5, larvitar: 5, bagon: 5, beldum: 5, gible: 5, deino: 5, goomy: 5,
	jangmoo: 5, dreepy: 5, frigibax: 5, nihilego: 5, buzzwole: 5, pheromosa: 5,
	xurkitree: 5, celesteela: 5, kartana: 5, guzzlord: 5, poipole: 5, stakataka: 5,
	blacephalon: 5, greattusk: 5, screamtail: 5, brutebonnet: 5, fluttermane: 5,
	slitherwing: 5, sandyshocks: 5, irontreads: 5, ironbundle: 5, ironhands: 5,
	ironjugulis: 5, ironmoth: 5, ironthorns: 5, roaringmoon: 5, ironvaliant: 5,
	typenull: 5, phione: 5, ogerpon: 5,
	okidogi: 5, munkidori: 5, fezandipiti: 5,
	walkingwake: 5, ironleaves: 5, gougingfire: 5, ragingbolt: 5, ironboulder: 5, ironcrown: 5,

	articuno: 6, zapdos: 6, moltres: 6, raikou: 6, entei: 6, suicune: 6,
	regirock: 6, regice: 6, registeel: 6, latias: 6, latios: 6, uxie: 6,
	mesprit: 6, azelf: 6, heatran: 6, cresselia: 6, cobalion: 6, terrakion: 6,
	virizion: 6, tornadus: 6, thundurus: 6, landorus: 6, tapukoko: 6, tapulele: 6,
	tapubulu: 6, tapufini: 6,
	articunogalar: 6, zapdosgalar: 6, moltresgalar: 6,
	regieleki: 6, regidrago: 6, enamorus: 6,
	glastrier: 6, spectrier: 6,
	wochien: 6, chienpao: 6, tinglu: 6, chiyu: 6,

	mewtwo: 7, mew: 7, lugia: 7, hooh: 7, celebi: 7, jirachi: 7, deoxys: 7,
	dialga: 7, palkia: 7, giratina: 7, manaphy: 7, darkrai: 7, shaymin: 7,
	reshiram: 7, zekrom: 7, kyurem: 7, xerneas: 7, yveltal: 7, zygarde: 7,
	cosmog: 7, necrozma: 7, zacian: 7, zamazenta: 7, koraidon: 7, miraidon: 7,
	keldeo: 7, meloetta: 7, genesect: 7, victini: 7, diancie: 7, hoopa: 7,
	volcanion: 7, magearna: 7, marshadow: 7, zeraora: 7, kubfu: 7, zarude: 7,
	calyrex: 7, pecharunt: 7,

	kyogre: 8, groudon: 8, rayquaza: 8, arceus: 8, eternatus: 8, terapagos: 8,
};

export function getStarterCost(species: string): number {
	const id = species.toLowerCase().replace(/[^a-z0-9]/g, '');
	return STARTER_COSTS[id] || 3;
}
